Added support for setups and so much more
* Created a `setup` function
* Created `remove_setup` function
* Added the first supported setup: 'qemu'
* Added `REQUIRE_PACKAGES` to ensure the user has things like
  bash and grep installed before the script will even run to
  prevent any unpredictable edge cases
* Replace many echo statements with printf as that is my new prefered
  default. Entirely replaced `display_help` echos with printf

diff --git a/arch b/arch
--- a/arch
+++ b/arch
@@ -23,6 +23,14 @@
 #  configured to my setup much easier.
 #
 
+SCRIPT_NAME="arch"
+
+REQUIRED_PACKAGES=( \
+    bash pacman \
+    usermod gpasswd groups \
+    grep cat \
+)
+
 INSTALLABLE_PACKAGES="\
     yay qutebrowser librewolf docker rust python \
 "
@@ -41,68 +49,92 @@ PRETTY_OUTPUT_LIBRARY=pretty_output_library.sh
 check_library_files_exist() {
     if ! [[ -f "./$PRETTY_OUTPUT_LIBRARY" ]]
     then
-        echo -e "\n - Missing pretty output script. Cannot Proceed - \n"
+        printf "\n\e[31m%s\e[0m\n" \
+            "[!] Missing pretty output script. Cannot Proceed"
         exit 4
     fi
     if ! [[ -f "./$PACKAGE_INSTALLATION_LIBRARY" ]]
     then
-        echo -e "\n - Missing package installation scripts. Cannot Proceed - \n"
+        printf "\n\e[31m%s\e[0m\n" \
+            "[!] Missing package installation scripts. Cannot Proceed"
         exit 4
     fi
     if ! [[ -f "./$SETUP_INSTALLATION_LIBRARY" ]]
     then
-        echo -e "\n - Missing setup installation scripts. Cannot Proceed - \n"
+        printf "\n\e[31m%s\e[0m\n" \
+            "[!] Missing setup installation scripts. Cannot Proceed"
         exit 4
     fi
 }
 
-check_library_files_exist
+check_packages()
+{
+    for tool in ${REQUIRED_PACKAGES[@]}
+    do
+        if ! { which $tool || type $tool; } &>/dev/null
+        then
+            printf "\n\e[31m%s\e[0m\n" "[!] Must install '$tool' for $SCRIPT_NAME to work"
+            tools_not_installed=1
+        fi
+    done
+
+    if ((tools_not_installed))
+    then
+        exit 6
+    fi
+}
 
 display_help() {
-    echo -e "\nUsage: arch [COMMAND]"
-    echo -e "\nSimplifies Arch-Setup and Arch-Configurations into a single"
-    echo -e " CLI tool with many more automated features.\n"
+    printf "\nUsage: $SCRIPT_NAME [COMMAND]"
+    printf "\n\n  %s\n  %s" \
+        "Simplifies Arch-Setup and Arch-Configurations into a single" \
+        "CLI tool with many more automated features."
 
-    echo "Commands:"
-    printf "\t%-15s %-1s\n" "install" "Install supported software"
-    printf "\t%-15s %-1s\n" "uninstall" "Cleanly uninstall supported software"
-    printf "\t%-15s %-1s\n" "setup" "Setup the system in specific ways"
-    printf "\t%-15s %-1s\n" "version" "Returns version information"
+    printf "\n\nCommands:"
+    printf "\n  %-15s %-1s" "install" "Install supported software"
+    printf "\n  %-15s %-1s" "uninstall" "Cleanly uninstall supported software"
+    printf "\n  %-15s %-1s" "setup" "Setup the system in specific ways"
+    printf "\n  %-15s %-1s" "remove-setup" "Remove a setup"
+    printf "\n  %-15s %-1s" "version" "Returns version information"
 
-    echo -e "\n(\`install\` is for tools you use directly: rust, docker, qutebrowser)"
-    echo "(\`setup\` is for set it and forget it defaults: security, river, bluetooth)"
-    echo "- The difference isn't all that large, but it's there. -"
+    printf "\n\n%s" \
+        "(\`install\` is for tools you use directly: rust, docker, qutebrowser)"
+    printf "\n%s" \
+        "(\`setup\` is for set it and forget it defaults: security, river, bluetooth)"
 
-    echo -e "\nBase Flags:"
-    printf "\t    %-20s\t %-1s\n" "--version" "Returns version information"
-    printf "\t    %-20s\t %-1s\n" "-h | --help" "Show this help message"
+    printf "\n\nBase Flags:"
+    printf "\n  %-20s %-1s" "--version" "Returns version information"
+    printf "\n  %-20s %-1s" "-h | --help" "Show this help message"
 
-    echo -e "\nCommand Flags:\n"
-    echo -e "\tinstall:"
-    printf "\t    %-20s\t %-1s\n" "-l | --list" "List installable software"
-    echo -e "\tuninstall:"
-    printf "\t    %-20s\t %-1s\n" "-l | --list" "List installed software"
-    echo -e "\tsetup:"
-    printf "\t    %-20s\t %-1s\n" "-l | --list" "List available setup options"
-    echo -e "\tunsetup:"
-    printf "\t    %-20s\t %-1s\n" "-l | --list" "List options already setup"
+    printf "\n\nCommand Flags:"
+    printf "\n  install:"
+    printf "\n    %-20s %-1s" "-l | --list" "List installable software"
+    printf "\n  uninstall:"
+    printf "\n    %-20s %-1s" "-l | --list" "List installed software"
+    printf "\n  setup:"
+    printf "\n    %-20s %-1s" "-l | --list" "List available setup options"
     
-    echo -e "\nExamples:"
-    echo -e "\t\`arch install --list\`"
-    echo -e "\t\`arch uninstall --list\`"
-    echo -e "\t\`arch install qutebrowser\`"
-    echo -e "\t\`arch install rust qemu docker\`"
-    echo -e "\t\`arch uninstall qutebrowser\`"
-    echo -e "\t\`arch setup river bluetooth\`"
-    echo -e "\t\`arch setup security user-scripts\`"
-    echo -e "\t\`arch unsetup rust\`"
+    printf "\n\nExamples:"
+    printf "\n  \`$SCRIPT_NAME install --list\`"
+    printf "\n  \`$SCRIPT_NAME uninstall --list\`"
+    printf "\n  \`$SCRIPT_NAME install qutebrowser\`"
+    printf "\n  \`$SCRIPT_NAME install rust qemu docker\`"
+    printf "\n  \`$SCRIPT_NAME uninstall qutebrowser\`"
+    printf "\n  \`$SCRIPT_NAME setup river bluetooth\`"
+    printf "\n  \`$SCRIPT_NAME setup security user-scripts\`"
+    printf "\n  \`$SCRIPT_NAME remove-setup rust\`"
 
-    echo -e "\nError Codes:"
-    printf "\t%-3s %-1s\n" "1" "Invalid command"
-    printf "\t%-3s %-1s\n" "2" "Package, setup, or preset doesn't exist"
-    printf "\t%-3s %-1s\n" "3" "Can't be uninstalled or removed as it doesn't exist or isn't installed"
-    printf "\t%-3s %-1s\n" "4" "Missing source file in Arch-Setup"
-    printf "\t%-3s %-1s\n" "5" "Package, setup, or preset depends on one or many other arch commands being run first"
+    printf "\n\nError Codes:"
+    printf "\n  %-3s %-1s" "1" "Invalid command"
+    printf "\n  %-3s %-1s" "2" "Package, setup, or preset doesn't exist"
+    printf "\n  %-3s %-1s\n      %s" "3" \
+        "Can't be uninstalled or removed as it doesn't exist or" \
+        "isn't installed"
+    printf "\n  %-3s %-1s" "4" "Missing source file for $SCRIPT_NAME"
+    printf "\n  %-3s %-1s\n      %s" "5" \
+        "Package, setup, or preset depends on one or many other" \
+        "$SCRIPT_NAME commands being run first"
+    printf "\n  %-3s %-1s" "6" "Missing package required by script"
 }
 
 install() {
@@ -115,7 +147,8 @@ install() {
         case $arg in
             "-l" | "--list")
                 [[ -n "$FLAG_list_packages" ]] && {
-                    echo -e "\n - [ERROR] duplicated the list packages flag - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] duplicated the list packages flag"
                     exit 1
                 }
                 FLAG_list_packages=1
@@ -125,7 +158,8 @@ install() {
                 # the catchall case
                 if [[ $arg =~ ^-{1,2} ]]
                 then
-                    echo "The '$arg' flag isn't supported"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] The '$arg' flag isn't supported"
                     exit 1
                 fi
                 packages_to_install+=($arg)
@@ -135,7 +169,7 @@ install() {
 
     if ((FLAG_list_packages))
     then
-        echo -e "\nPackages Available to Install:"
+        printf "\nPackages Available to Install:\n"
         for package_name in $INSTALLABLE_PACKAGES
         do
             echo "  - $package_name"
@@ -143,7 +177,10 @@ install() {
         
         if [[ -n $packages_to_install ]]
         then
-            echo -e "\nTIP: cannot list packages and install in the same command"
+            printf "\n\e[31m%s %s\e[0m\n" \
+                "[!] Cannot list installable packages" \
+                "and install packages in the same command"
+            exit 1
         fi
 
         exit 0
@@ -153,8 +190,9 @@ install() {
     do
         if ! echo "$INSTALLABLE_PACKAGES" | grep "$package_name" &>/dev/null
         then
-            echo -e "\n'$package_name' is not a supported package"
-            echo -e "\nTIP: run \`arch install --list\` to see supported packages"
+            printf "\n\e[31m%s\n%s\e[0m\n" \
+                "[!] '$package_name' is not a supported package" \
+                " - TIP: run \`arch install --list\` to see supported packages"
             exit 2
         fi
     done
@@ -167,41 +205,49 @@ install() {
             "yay")
                 if ! install_yay
                 then
-                    echo -e "\n - Failed to install yay - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to install yay"
                 fi
             ;;
             "qutebrowser")
                 if ! install_qutebrowser
                 then
-                    echo -e "\n - Failed to install qutebrowser - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to install qutebrowser"
                 fi
             ;;
             "librewolf")
                 if ! install_librewolf
                 then
-                    echo -e "\n - Failed to install librewolf - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to install librewolf"
                 fi
             ;;
             "docker")
                 if ! install_docker
                 then
-                    echo -e "\n - Failed to install docker - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to install docker"
                 fi
             ;;
             "python")
                 if ! install_python
                 then
-                    echo -e "\n - Failed to install python - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to install python"
                 fi
             ;;
             "rust")
                 if ! install_rust
                 then
-                    echo -e "\n - Failed to install rust - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to install rust"
                 fi
             ;;
             *)
-                echo "This shouldn't happen..."
+                printf "\n\e[31m%s %s\e[0m\n" \
+                    "[!] Chosen packages did not match installation case statement." \
+                    "This shouldn't happen...stopping"
                 exit 1
             ;;
         esac
@@ -218,7 +264,8 @@ uninstall() {
         case $arg in
             "-l" | "--list")
                 [[ -n "$FLAG_list_packages" ]] && {
-                    echo -e "\n - [ERROR] duplicated the list packages flag - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] duplicated the list installed packages flag"
                     exit 1
                 }
                 FLAG_list_packages=1
@@ -228,7 +275,8 @@ uninstall() {
                 # the catchall case
                 if [[ $arg =~ ^-{1,2} ]]
                 then
-                    echo "The '$arg' flag isn't supported"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] The '$arg' flag isn't supported"
                     exit 1
                 fi
                 packages_to_uninstall+=($arg)
@@ -238,7 +286,7 @@ uninstall() {
 
     if ((FLAG_list_packages))
     then
-        echo -e "\nInstalled Packages:"
+        printf "\nInstalled Packages:\n"
         for package_name in $INSTALLABLE_PACKAGES
         do
             if ! { which yay || type yay; } &>/dev/null
@@ -257,7 +305,9 @@ uninstall() {
         
         if [[ -n $packages_to_uninstall ]]
         then
-            echo -e "\nTIP: cannot list packages and uninstall in the same command"
+            printf "\n\e[31m%s\e[0m" \
+                "[!] Cannot list and uninstall packages in the same command"
+            exit 1
         fi
 
         exit 0
@@ -267,8 +317,9 @@ uninstall() {
     do
         if ! echo "$INSTALLABLE_PACKAGES" | grep "$package_name" &>/dev/null
         then
-            echo -e "\n'$package_name' is not a supported package"
-            echo -e "\nTIP: run \`arch uninstall --list\` to see supported packages"
+            printf "\n\e[31m%s\n%s\e[0m\n" \
+                "[!] '$package_name' is not a supported package" \
+                " - TIP: run \`arch uninstall --list\` to see supported packages"
             exit 3
         fi
 
@@ -277,8 +328,10 @@ uninstall() {
         then
             if ! yay -Q $package_name &>/dev/null
             then
-                echo -e "\n'$package_name' is not installed"
-                echo -e "\nTIP: run \`arch uninstall --list\` to see installed packages"
+                printf "\n\e[31m%s\n%s %s\e[0m\n" \
+                    "[!] '$package_name' is not installed" \
+                    " - TIP: run \`arch uninstall --list\` to see" \
+                    "installed packages"
                 exit 3
             fi
         fi
@@ -299,60 +352,202 @@ uninstall() {
             "yay")
                 if ! uninstall_yay
                 then
-                    echo -e "\n - Failed to uninstall yay - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to uninstall yay"
                 fi
             ;;
             "qutebrowser")
                 if ! uninstall_qutebrowser
                 then
-                    echo -e "\n - Failed to uninstall qutebrowser - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to uninstall qutebrowser"
                 fi
             ;;
             "librewolf")
                 if ! uninstall_librewolf
                 then
-                    echo -e "\n - Failed to uninstall librewolf - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to uninstall librewolf"
                 fi
             ;;
             "docker")
                 if ! uninstall_docker
                 then
-                    echo -e "\n - Failed to uninstall docker - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to uninstall docker"
                 fi
             ;;
             "python")
                 if ! uninstall_python
                 then
-                    echo -e "\n - Failed to uninstall python - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to uninstall python"
                 fi
             ;;
             "rust")
                 if ! uninstall_rust
                 then
-                    echo -e "\n - Failed to uninstall rust - \n"
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to uninstall rust"
                 fi
             ;;
             *)
-                echo "This shouldn't happen..."
+                printf "\n\e[31m%s %s\e[0m\n" \
+                    "[!] Chosen packages did not match uninstall case statement." \
+                    "This shouldn't happen...stopping"
                 exit 1
             ;;
         esac
     done
 }
 
-place_holder() {
-    echo $@
+setup() {
+    local \
+        setups_chosen \
+        FLAG_list_packages
+
+    for arg in $@
+    do
+        case $arg in
+            "-l" | "--list")
+                [[ -n "$FLAG_list_packages" ]] && {
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] duplicated the list setups flag"
+                    exit 1
+                }
+                FLAG_list_setups=1
+            ;;
+            *)
+                # Support flags starting with '-' or "--" shouldn't reach
+                # the catchall case
+                if [[ $arg =~ ^-{1,2} ]]
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] The '$arg' flag isn't supported"
+                    exit 1
+                fi
+                setups_chosen+=($arg)
+            ;;
+        esac
+    done
+
+    if ((FLAG_list_setups))
+    then
+        printf "\nAvailable Setup Options:"
+        for setup_name in $SETUP_OPTIONS
+        do
+            echo "  - $setup_name"
+        done
+
+        if [[ -n $setups_chosen ]]
+        then
+            printf "\n\e[31m%s %s\e[0m\n" \
+                "[!] Cannot list setup options and" \
+                "set them up in the same command"
+        fi
+
+        exit 0
+    fi
+
+    for setup_name in ${setups_chosen[@]}
+    do
+        if ! echo "$SETUP_OPTIONS" | grep "$setup_name" &>/dev/null
+        then
+            printf "\n\n\e[31m%s\n\t%s\e[0m\n" \
+                "[!] '$setup_name' is not a supported setup" \
+                " - TIP: run \`arch setup --list\` to see supported setups"
+            exit 2
+        fi
+    done
+
+    source ./$SETUP_INSTALLATION_LIBRARY || check_library_files_exist
+
+    for setup_name in ${setups_chosen[@]}
+    do
+        case $package_name in
+            "qemu")
+                if ! setup_qemu
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to setup qemu"
+                fi
+            ;;
+            *)
+                printf "\e[31m%s %s\e[0m" \
+                    "Chosen setups did not match setup case statement." \
+                    "This shouldn't happen...stopping"
+                exit 1
+            ;;
+        esac
+    done
 }
+
+remove_setup() {
+    local \
+        setups_chosen \
+
+    for arg in $@
+    do
+        case $arg in
+            *)
+                # Support flags starting with '-' or "--" shouldn't reach
+                # the catchall case
+                if [[ $arg =~ ^-{1,2} ]]
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] The '$arg' flag isn't supported"
+                    exit 1
+                fi
+                setups_chosen+=($arg)
+            ;;
+        esac
+    done
+
+    for setup_name in ${setups_chosen[@]}
+    do
+        if ! echo "$SETUP_OPTIONS" | grep "$setup_name" &>/dev/null
+        then
+            printf "\n\e[31m%s\n%s\e[0m\n" \
+                "[!] '$setup_name' is not a supported setup option" \
+                " - TIP: run \`arch setup --list\` to see supported setup options"
+            exit 3
+        fi
+    done
+
+    source ./$PACKAGE_INSTALLATION_LIBRARY || check_library_files_exist
+
+    for setup_name in ${setups_chosen[@]}
+    do
+        case $setup_name in
+            "qemu")
+                if ! remove_setup_qemu
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to remove setup: qemu"
+                fi
+            ;;
+            *)
+                printf "\n\e[31m%s %s\e[0m\n" \
+                    "[!] Chosen setup did not match remove setup case statement." \
+                    "This shouldn't happen...stopping"
+                exit 1
+            ;;
+        esac
+    done
+}
+
+check_packages
+check_library_files_exist
 
 case $1 in
     "install")      install ${@:2};;
     "uninstall")    uninstall ${@:2};;
-    "setup")        place_holder ${@:2};;
-    "preset")       place_holder ${@:2};;
+    "setup")        setup ${@:2};;
+    "remove-setup")      remove_setup ${@:2};;
     "version"|"--version") echo "0.1.0";;
     "--help"|"-h") display_help;;
     *) 
-        echo -e "\n - [ERROR] Invalid use of the \`arch\` command -";
+        printf "\n\n - [ERROR] Invalid use of the \`arch\` command -";
         display_help
         exit 1
         ;;
