Major `notes` & `move` script improvements, +more
Added weather, a --all flag, and upgrade the network logic in
update-status-bar. Removed the `prevent-screen-sleep` script in favor of
having logic directly in the `.xinitrc` that pauses any play audio if
the screen locks. Made the logic in the `notes` and `move` script much
more robust.

diff --git a/DoNotRun/scripts/dwm_scripts/update-status-bar b/DoNotRun/scripts/dwm_scripts/update-status-bar
--- a/DoNotRun/scripts/dwm_scripts/update-status-bar
+++ b/DoNotRun/scripts/dwm_scripts/update-status-bar
@@ -23,6 +23,7 @@ update-status-bar() {
     CACHE_VOLUME_FILE=$CACHE_DIRECTORY/volume_display.log
     CACHE_BATTERY_FILE=$CACHE_DIRECTORY/battery_display.log
     CACHE_NETWORK_FILE=$CACHE_DIRECTORY/network_display.log
+    CACHE_WEATHER_FILE=$CACHE_DIRECTORY/weather_display.log
     mkdir -p $CACHE_DIRECTORY 
     [[ -f $CACHE_DIRECTORY/brightness_display.log ]] \
         && brightness_display=$(cat $CACHE_BRIGHTNESS_FILE) \
@@ -36,6 +37,9 @@ update-status-bar() {
     [[ -f $CACHE_DIRECTORY/network_display.log ]] \
         && network_display=$(cat $CACHE_NETWORK_FILE) \
         || echo "" > $CACHE_NETWORK_FILE
+    [[ -f $CACHE_DIRECTORY/weather_display.log ]] \
+        && weather_display=$(cat $CACHE_WEATHER_FILE) \
+        || echo "" > $CACHE_WEATHER_FILE
 
     # unset flag variables before match, for safety
     unset brightness_flag \
@@ -49,6 +53,19 @@ update-status-bar() {
     for arg in "${@}";
     do
         case $arg in
+            "--all")
+                [[ -n "$all_flag" ]] && {
+                    echo -e "\n - [ERROR] duplicated the brightness flag - \n"
+                    exit 1
+                }
+                all_flag=true
+
+                brightness_flag=true
+                volume_flag=true
+                battery_flag=true
+                network_flag=true
+                weather_flag=true
+            ;;
             "--brightness")
                 [[ -n "$brightness_flag" ]] && {
                     echo -e "\n - [ERROR] duplicated the brightness flag - \n"
@@ -77,11 +94,19 @@ update-status-bar() {
                 }
                 network_flag=true
             ;;
+            "--weather")
+                [[ -n "$weather_flag" ]] && {
+                    echo -e "\n - [ERROR] duplicated the weather flag - \n"
+                    exit 1
+                }
+                weather_flag=true
+            ;;
         esac
     done
 
     if [[ $brightness_flag == true ]]
     then
+        unset brightness_display
         brightness_percentage=$(brightness)
         [[ -n $brightness_percentage ]] && brightness_display="bri: $brightness_percentage |"
         echo "$brightness_display" > $CACHE_BRIGHTNESS_FILE
@@ -90,6 +115,7 @@ update-status-bar() {
 
     if [[ $volume_flag == true ]]
     then
+        unset volume_display
         volume_percentage=$(volume)
         [[ -n $volume_percentage ]] && volume_display="vol: $volume_percentage% |"
         echo "$volume_display" > $CACHE_VOLUME_FILE
@@ -98,6 +124,7 @@ update-status-bar() {
 
     if [[ $battery_flag == true ]]
     then
+        unset battery_display
         # Get all batteries with capacities
         batt_array=$(ls /sys/class/power_supply/*/capacity)
         # Take the first battery with a capacity value as the default
@@ -115,6 +142,7 @@ update-status-bar() {
 
     if [[ $network_flag == true ]]
     then
+        unset network_display
         #
         # Calculates the rx and tx usage of the network
         #
@@ -142,26 +170,42 @@ update-status-bar() {
         #
         nmcli_device_output=$(nmcli d)
 
-        if [[ "$nmcli_device_output" =~ "ethernet " ]]
-        then
-            ethernet_output=$(echo "$nmcli_device_output" | grep 'ethernet ')
-            ssid=$(echo "$ethernet_output" | awk '{$1=$2=$3=""; print $0}' | awk '{$1=$1; print}')
-            # If the ethernet interface is connected to a network
-            [[ $ssid =~ "--" ]] || network_display="eth:$current_combined_usage:$ssid |"
-        fi
+        for interface in 'ethernet' 'wifi'
+        do
+            devices="$(echo "$nmcli_device_output" | grep "$interface ")"
+            ssids="$(echo "$devices" | awk '{$1=$2=$3=""; print $0}' | awk '{$1=$1; print}')"
+            while IFS= read -r ssid
+            do
+                if ! echo "$ssid" | grep "\--" &>/dev/null
+                then
+                    network_display="$interface:$current_combined_usage:$ssid |"
+                fi
+            done < <(echo "$ssids")
+        done
 
-        if [[ "$nmcli_device_output" =~ "wifi " ]]
-        then
-            wifi_output=$(echo "$nmcli_device_output" | grep 'wifi ')
-            ssid=$(echo "$wifi_output" | awk '{$1=$2=$3=""; print $0}' | awk '{$1=$1; print}')
-            # If the wifi interface is connected to a network
-            [[ $ssid =~ "--" ]] || network_display="wifi:$current_combined_usage:$ssid |"
-        fi
         echo "$network_display" > $CACHE_NETWORK_FILE
     fi
+    
 
+    if [[ $weather_flag == true && -n "$LOCATION" ]]
+    then
+        unset $weather_display
+        echo "$weather_display" > $CACHE_WEATHER_FILE
 
-    xsetroot -name "$brightness_display $volume_display $battery_display $network_display $(date +"%B %e %H:%M:%S")"
+        weather_data="$(curl -s wttr.in/columbus_nebraska?u\&format=%t+%w)"
+        if [[ $? == 0 ]]
+        then
+            if ! echo "$weather_data" | grep -i "Sorry" &>/dev/null
+            then
+                real_temperature=$(echo "$weather_data" | awk '{print $1}')
+                wind_speed=$(echo "$weather_data" | awk '{print $2}')
+                weather_display="$real_temperature ($wind_speed) |"
+                echo "$weather_display" > $CACHE_WEATHER_FILE
+            fi
+        fi
+    fi
+
+    xsetroot -name "$brightness_display $volume_display $battery_display $network_display $weather_display $(date +"%B %e %H:%M:%S")"
 }
 
 update-status-bar $@
diff --git a/DoNotRun/scripts/general_scripts/move b/DoNotRun/scripts/general_scripts/move
--- a/DoNotRun/scripts/general_scripts/move
+++ b/DoNotRun/scripts/general_scripts/move
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # move - part of the Arch-Setup project
-# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
+# Copyright (C) 2024, JustScott, development@justscott.me
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -21,68 +21,30 @@
 #
 
 
+# remove '/tmp/' once stable (and change 'example')
+#  (or change to $HOME/<name> ?
+BACKUP_FILE_BASENAME=packed_system
+
 DATA_DIRECTORY=$HOME/.config/move
 BACKUP_PATHS_FILE=$DATA_DIRECTORY/backup_paths
 
-[[ -d $DATA_DIRECTORY ]] || {
-    echo -e "\n - [ERROR] $DATA_DIRECTORY doesn't exist... creating & exiting - \n"
-    mkdir -p $DATA_DIRECTORY
-    exit 1
-}
+SUPPORTED_APPS_TEMP_PATH=/tmp/move_supported_app_files
+mkdir -p $SUPPORTED_APPS_TEMP_PATH
 
 
 display_help() {
     echo -e "\nUsage: move [COMMAND]"
-    echo -e "\nA script for backing up and moving your important files"
+    echo -e "\nMove or backup all your important files in an encrypted tar.gz archive"
 
-    echo "Commands:"
-    printf "\t%-15s %-1s\n" "list" "displays all files & directories to be backed up"
+    echo -e "\nCommands:"
     printf "\t%-15s %-1s\n" "pack" "'packs' all your files into a single directory or compressed file, ready for moving" 
     printf "\t%-15s %-1s\n" "unpack" "'unpacks' all your files and places them around the system" 
     printf "\t%-15s %-1s\n" "version" "Returns version information"
 
-    echo -e "\nCommand Flags:\n"
-    echo -e "\tlist:"
-    printf "\t    %-20s\t %-1s\n" "-c | --custom-apps" "Display file and directories to be backed up for all supported custom apps"
-    printf "\t    %-20s\t %-1s\n" "-a | --all" "Display "
-    echo -e "\tpack:"
-    printf "\t    %-20s\t %-1s\n" "-c | --compress" "Compress all your files & directories into a single tar file"
-    printf "\t    %-20s\t %-1s\n" "-e | --encrypt" "Automatically encrypt the compressed backup file (must also pass the compress flag)"
-    printf "\t    %-20s\t %-1s\n" "-C | --clean" "Deletes the original tar file after encryption, keeping only the encrypt tar file (must also pass the compress flag)"
-    echo -e "\tunpack:"
-    printf "\t    %-20s\t %-1s\n" "-y | --noconfirm" "skip the 'are you sure' prompt"
-    printf "\t    %-20s\t %-1s\n" "--undo" "quickly undo the changes made by the last unpack command"
-    
     echo -e "\nExamples:"
     echo -e "\t\`move pack\`"
 
-    echo -e "\nError Codes:"
-    printf "\t%-3s %-1s\n" "1" "Invalid command"
-    printf "\t%-3s %-1s\n" "2" "Package doesn't exist"
-    printf "\t%-3s %-1s\n" "3" "Missing dependencies"
-
     echo ""
-}
-
-
-compress() {
-    if [[ -f $BACKUP_PATHS_FILE ]]
-    then
-        source $BACKUP_PATHS_FILE # imports the 'paths' array
-
-        cp /tmp/example.tar.aes.gz /tmp/example.tar.aes.gz.bak &>/dev/null
-
-        # Verify all paths exist
-        for path in ${paths[@]};
-        do
-            [[ -d $path || -f $path ]] || {
-                echo -e "\n - [ERROR] $path from $BACKUP_PATHS_FILE doesn't exist - \n"
-                exit 1
-            }
-        done
-
-        tar -czf /tmp/example.tar ${paths[@]}
-    fi
 }
 
 encrypt() {
@@ -90,11 +52,11 @@ encrypt() {
     do
         openssl enc \
             -a -aes-256-cbc -pbkdf2 --iter 1000000 \
-            -in host_backup.tar -out host_backup.tar.aes 2> /dev/null
+            -in $1 -out $1.aes 2> /dev/null
 
         # Only exit the loop if the encryption succeeds
         [[ $? == 0 ]] \
-            && break \
+            && return 0 \
             || echo -e "\n - Encryption keys don't match... try again - \n"
     done
 }
@@ -102,18 +64,30 @@ encrypt() {
 #
 # If a supported app is installed, back it up
 #
-calurse_pack() {
+calcurse_pack() {
     { which calcurse || type calcurse; } &>/dev/null && {
-        [[ -d $HOME/.config/calcurse ]] && {
-            echo "under construction"
+        calcurse --export > $SUPPORTED_APPS_TEMP_PATH/calcurse.ical
     }
 }
-
-custom_app_pack() {
-    calurse_pack
-}
+#notes_pack() {
+#    { which notes || type notes; } &>/dev/null && {
+#        if [[ -d $HOME/notes ]]
+#        then
+#            notes pack
+#            return 0
+#        else
+#            return 1
+#        fi
+#    }
+#}
 
 pack() {
+    [[ -d $DATA_DIRECTORY ]] || {
+        echo -e "\n - [ERROR] $DATA_DIRECTORY doesn't exist... creating & exiting - \n"
+        mkdir -p $DATA_DIRECTORY
+        exit 1
+    }
+
     # unset flag variables before match, for safety
     local unset skipped_command_input
 
@@ -135,15 +109,95 @@ pack() {
                     skipped_command_input=true
                     continue
                 }
-
-                local package_names+=($arg)
             ;;
         esac
     done
+
+
+    if ! [[ -f $BACKUP_PATHS_FILE ]]
+    then
+        echo "[ERROR] Must create a '$BACKUP_PATHS_FILE' file first"
+        return 1
+    fi
+
+    # Save backup of existing packed file incase the current pack fails
+    [[ -f $BACKUP_FILE_BASENAME.tar.aes.gz ]] \
+        && cp $BACKUP_FILE_BASENAME.tar.aes.gz $BACKUP_FILE_BASENAME.tar.aes.gz.bak &>/dev/null
+
+    source $BACKUP_PATHS_FILE # imports the 'paths' array
+    
+
+    calcurse_pack
+    #notes_pack && paths+=($HOME/packed_notes.tar.aes)
+
+    paths+=($SUPPORTED_APPS_TEMP_PATH)
+
+    ORIGINAL_PWD=$PWD
+    cd / # Ensure the user provided full paths from root
+    # Verify all paths exist
+    for path in ${paths[@]}
+    do
+        [[ -d $path || -f $path ]] || {
+            echo -e "\n - [ERROR] $path from 'backup_paths' doesn't exist (must provide full path from '/') - \n"
+            exit 1
+        }
+    done
+    cd $ORIGINAL_PWD
+
+    if tar -czf $BACKUP_FILE_BASENAME.tar.gz ${paths[@]}
+    then
+        echo "Encrypting compressed backup file..."
+        if encrypt $BACKUP_FILE_BASENAME.tar.gz
+        then
+            shred -uz $BACKUP_FILE_BASENAME.tar.gz
+            echo -e "\n - [SUCCESS] File packed to: $BACKUP_FILE_BASENAME.tar.gz.aes - \n"
+            return 0
+        else
+            echo -e "\n - [ERROR] Couldn't encrypt compressed file: '$BACKUP_FILE_BASENAME.tar.gz' - \n"
+            [[ -f $BACKUP_FILE_BASENAME.tar.aes.gz.bak ]] \
+                && cp $BACKUP_FILE_BASENAME.tar.aes.gz.bak $BACKUP_FILE_BASENAME.tar.aes.gz
+            return 1
+        fi
+    else
+        echo -e "\n - [ERROR] compression failed! - \n"
+        [[ -f $BACKUP_FILE_BASENAME.tar.aes.gz.bak ]] \
+            && cp $BACKUP_FILE_BASENAME.tar.aes.gz.bak $BACKUP_FILE_BASENAME.tar.aes.gz
+        return 1
+    fi
 }
 
 
+######################################
 
+calcurse_unpack() {
+    if { which calcurse || type calcurse; } &>/dev/null
+    then
+        if [[ -f $SUPPORTED_APPS_TEMP_PATH/calcurse.ical ]]
+        then
+            mkdir -p $HOME/.config/calcurse
+            # Save an infinite number of backups, as to not lose any data by accident
+            calcurse_backup_file_path="$HOME/.config/calcurse/calcurse-$(date +"%B-%e_%H-%M-%S").ical.bak"
+            if calcurse --export > $calcurse_backup_file_path
+            then
+                echo "Created a backup of your existing calcurse ical data at: '$calcurse_backup_file_path'"
+                rm -rf $HOME/.local/share/calcurse/* || {
+                    echo "[ERROR] Failed to remove existing calcurse data... stopping to prevent duplicating data"
+                    echo -e "\n\t* Your packed calcurse.ical file is stored at $SUPPORTED_APPS_TEMP_PATH if you'd"
+                    echo -e "\t     like to manually import the data"
+                }
+            fi
+
+            if calcurse --import $SUPPORTED_APPS_TEMP_PATH/calcurse.ical &>/dev/null
+            then
+                echo "Packed calcurse.ical file imported!"
+                return 0
+            else
+                echo "[ERROR] Failed to import calcurse ical data stored at: '$SUPPORTED_APPS_TEMP_PATH/calcurse.ical'"
+                return 1
+            fi
+        fi
+    fi
+}
 
 unpack() {
     # unset flag variables before match, for safety
@@ -167,20 +221,58 @@ unpack() {
                     skipped_command_input=true
                     continue
                 }
-
-                local package_names+=($arg)
             ;;
         esac
     done
+
+
+    if ! [[ -f $BACKUP_FILE_BASENAME.tar.gz.aes ]]
+    then
+        echo "No '$BACKUP_FILE_BASENAME.tar.gz.aes' file found, exiting..."
+        return 1
+    fi
+
+    echo "Decrypting Backup..."
+    while :
+    do
+        # Decrypt the backup
+        openssl enc -d -a -aes-256-cbc -pbkdf2 --iter 1000000 \
+            -in $BACKUP_FILE_BASENAME.tar.gz.aes \
+            -out $BACKUP_FILE_BASENAME.tar.gz 2> /dev/null
+
+        tar --list --file $BACKUP_FILE_BASENAME.tar.gz &>/dev/null \
+            && break \
+            || echo -e "\n - Incorrect decryption key... try again - \n"
+    done
+
+    ORIGINAL_PWD=$PWD
+    cd / # must be in root since the user gives the full paths of files to pack
+
+    if tar -xf $ORIGINAL_PWD/$BACKUP_FILE_BASENAME.tar.gz &>/dev/null
+    then
+        shred -uz $ORIGINAL_PWD/$BACKUP_FILE_BASENAME.tar.gz
+        echo "Unpacked: '$BACKUP_FILE_BASENAME.tar.gz' successfully!"
+
+        calcurse_unpack
+
+        return 0
+    else
+        echo -e "\n[ERROR] Failed to decompress the unencrypted '$BACKUP_FILE_BASENAME.tar.gz' file"
+        echo -e "\n\t* If your \$HOME directory (your username) has changed since you've created"
+        echo -e "\t   $BACKUP_FILE_BASENAME.tar.gz.aes, consider changing your users home directory"
+        echo -e "\t   temporarily for the unpack. You can then run 'move pack' to create a new pack"
+        echo -e "\t   file with your current \$HOME directory."
+        return 1
+    fi
 }
 
 case $1 in
-    "pack")          check_packages; pack;;
-    "unpack")        check_packages; unpack;;
+    "pack")          pack;;
+    "unpack")        unpack;;
     "version"|"--version") echo "0.1.0";;
     ""|"--help"|"-h") display_help;;
     *) 
-        echo -e "\n - [ERROR] Invalid use of the \`vm\` command -";
+        echo -e "\n - [ERROR] Invalid use of the \`move\` command -";
         display_help
         exit 1
         ;;
diff --git a/DoNotRun/scripts/general_scripts/notes b/DoNotRun/scripts/general_scripts/notes
--- a/DoNotRun/scripts/general_scripts/notes
+++ b/DoNotRun/scripts/general_scripts/notes
@@ -1,7 +1,7 @@
 #!/bin/bash
 #
 # notes - part of the Arch-Setup project
-# Copyright (C) 2023, Scott Wyman, development@scottwyman.me
+# Copyright (C) 2024, JustScott, development@justscott.me
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU Affero General Public License as published by
@@ -16,25 +16,23 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
+PACKED_NOTES_BASENAME="packed_notes"
+
 ensure_notes_dir() {
     if [[ -d $HOME/notes ]]
     then
-        STARTING_PWD=$PWD
-        cd $HOME
+        return 0
     else
         echo "A 'notes' directory must be place in your home directory, exiting..."
-        cd $STARTING_PWD
-        exit 1
+        return 1
     fi
 }
 
 pack() {
-    ensure_notes_dir
-
     #
     # Capture flags
     #
-    for arg in "${@:2}";
+    for arg in "${@}";
     do
         case $arg in
             "--clean" | "-c")
@@ -42,45 +40,62 @@ pack() {
                     clean_flag=true
                 }
             ;;
+            *)
+                [[ "$arg" == "pack" && -z "$skipped_command_input" ]] && {
+                    skipped_command_input=true
+                    continue
+                }
+            ;;
         esac
     done
 
+    ORIGINAL_PWD=$PWD
+    cd $HOME
     echo "Compressing Notes..."
-    tar -czf packed_notes.tar notes
+    tar -czf $PACKED_NOTES_BASENAME.tar.gz notes
+
+    mv $PACKED_NOTES_BASENAME.tar.gz $ORIGINAL_PWD/ &>/dev/null
+    cd $ORIGINAL_PWD
 
     echo "Encrypting Notes..."
-    # Encrypt the backup for transport
-    openssl enc -a -aes-256-cbc -pbkdf2 --iter 1000000 -in packed_notes.tar -out packed_notes.tar.aes 2> /dev/null
 
-    # Exit if the user provides two different encryption keys
-    [[ $? != 0 ]] && {
-        echo "Encryption keys don't match, exiting..."
-        # Remove the unencrypted .tar file
-        shred -uz packed_notes.tar
-        cd $STARTING_PWD
-        exit 1
-    }
+    while :
+    do
+        # Encrypt the backup for transport
+        if openssl enc -a -aes-256-cbc -pbkdf2 --iter 1000000 \
+            -in $PACKED_NOTES_BASENAME.tar.gz \
+            -out $PACKED_NOTES_BASENAME.tar.gz.aes 2> /dev/null
+        then
+            good_encryption=true
+            break
+        else
+            echo -e "\n - Encryption keys don't match... try again - \n"
+        fi
+    done
 
-    # Remove the unencrypted .tar file
-    shred -uz packed_notes.tar
+    # Remove the unencrypted .tar.gz file
+    shred -uz $PACKED_NOTES_BASENAME.tar.gz
 
-    #
-    # Apply Flags
-    #
-    [[ $clean_flag == true ]] && rm -rf notes 
+    if [[ $good_encryption == true ]]
+    then
+        #
+        # Apply Flags
+        #
+        [[ $clean_flag == true ]] && rm -rf $HOME/notes 
 
-    cd $STARTING_PWD
+        echo "Notes packed to '$PACKED_NOTES_BASENAME.tar.gz.aes'"
+        return 0
+    else
+        echo "Had and issue encrypting '$PACKED_NOTES_BASENAME.tar.gz'"
+        return 1
+    fi
 }
 
 unpack() {
-    if [[ -a $HOME/packed_notes.tar.aes ]]
+    if ! [[ -f $PACKED_NOTES_BASENAME.tar.gz.aes ]]
     then
-        STARTING_PWD=$PWD
-        cd $HOME
-    else
-        echo "packed_notes.tar.aes must be place in your home directory, exiting..."
-        cd $STARTING_PWD
-        exit 1
+        echo "No '$PACKED_NOTES_BASENAME.tar.gz.aes' file found, exiting..."
+        return 1
     fi
 
     if [[ -d $HOME/notes ]]
@@ -88,34 +103,39 @@ unpack() {
         read -p "'$HOME/notes' already exists, are you sure you want to overwrite it? [y/N]: " overwrite_notes
         [[ $overwrite_notes == "y" || $overwrite_notes == "Y" || $overwrite_notes == "yes" ]] || {
             echo "Skipping unpack..."
-            exit
+            return 1
         }
     fi
 
     echo "Decrypting Notes..."
-    # Decrypt the backup
-    openssl enc -d -a -aes-256-cbc -pbkdf2 --iter 1000000 -in packed_notes.tar.aes -out packed_notes.tar 2> /dev/null
+    while :
+    do
+        # Decrypt the backup
+        openssl enc -d -a -aes-256-cbc -pbkdf2 --iter 1000000 \
+            -in $PACKED_NOTES_BASENAME.tar.gz.aes \
+            -out $PACKED_NOTES_BASENAME.tar.gz 2> /dev/null
 
-    # Exit if the wrong decryption key is given
-    [[ $? != 0 ]] && {
-        echo "Incorrect Decryption key"
-        # Remove the incorrectly decrypted archive file
-        shred -uz packed_notes.tar
-        cd $STARTING_PWD
-        exit 1
-    } 
+        # Test if the file was decrypted correctly
+        tar --list --file $PACKED_NOTES_BASENAME.tar.gz &>/dev/null \
+            && break \
+            || echo -e "\n - Incorrect decryption key... try again - \n"
+    done
 
-    # Unpack all my files into the current pwd
-    tar -xf packed_notes.tar
+    mv $PACKED_NOTES_BASENAME.tar.gz $HOME/ &>/dev/null
+    cd $HOME
 
-    # Remove the unencrypted .tar file
-    shred -uz packed_notes.tar
-
-    cd $STARTING_PWD
+    if tar -xf $PACKED_NOTES_BASENAME.tar.gz &>/dev/null
+    then
+        shred -uz $PACKED_NOTES_BASENAME.tar.gz
+        echo "Notes unpacked!"
+        return 0
+    else
+        echo "[ERROR] Failed to decompress the unencrypted '$PACKED_NOTES_BASENAME.tar.gz' file"
+        return 1
+    fi
 }
 
 open_notes() {
-    ensure_notes_dir
     if { which lf || type lf; } &>/dev/null
     then
         lf $HOME/notes
@@ -127,24 +147,30 @@ open_notes() {
 
 display_help() {
     echo -e "\nUsage: notes [COMMAND]"
-    echo -e "\nEasy management of encrypted notes in the terminal, with \`lf\` support"
+    echo -e "\nEasy management of encrypted notes in the terminal. Uses \`lf\` for note traversal"
 
-    echo "Commands:"
-    printf "\t%-10s %-10s\n" "pack" "Compress, encrypt, and store '$HOME/notes' in a <packed_notes>.tar.aes file"
-    printf "\t%-10s %-10s\n" "unpack" "Decompress, decrypt, and places <packed_notes>.tar.aes file into the '$HOME/notes' directory"
+    echo -e "\nCommands:"
+    printf "\t%-10s %-10s\n" "pack" "Compress and encrypt '\$HOME/notes' into a packed_notes.tar.gz.aes file"
+    printf "\t%-10s %-10s\n" "unpack" "Decrypt and decompress packed_notes.tar.gz.aes into the '\$HOME/notes' directory"
 
-    echo "Examples:"
-    echo -e "\t\`notes\` # opens notes in lf, or just changes to directory"
+    echo -e "\nCommand Flags:\n"
+    echo -e "\tpack:"
+    printf "\t    %-10s\t %-1s\n" "--clean" "removes '\$HOME/notes' after creating packed_notes.tar.gz.aes"
+
+    echo -e "\nExamples:"
+    echo -e "\t\`notes\` # opens notes in lf"
     echo -e "\t\`notes pack\`"
-    echo -e "\t\`notes pack --clean\` # removes '$HOME/notes' after creating <packed_notes>.tar.aes"
+    echo -e "\t\`notes pack --clean\`"
     echo -e "\t\`notes unpack\`"
+
+    echo ""
 }
 
 
 case $1 in
-    "pack")        pack $@;;
+    "pack")        ensure_notes_dir && pack $@;;
     "unpack")      unpack;;
-    "")            open_notes;;
+    "")            ensure_notes_dir && open_notes;;
     "--help"|"-h") display_help;;
     *)
         echo -e "\n - Invalid use of the \`notes\` command -";
