Completely Restructure Project (Breaking)
I'm moving entirely to gnome and removing anything related to prior
window manager scripts and/or configs. This doesn't mean I can't add a
new window manager in the future, it just means I'll need to implement
new scripts and configs from scratch. I wanted to completely remove
anything I don't use anymore, which included many functions, scripts,
directories, etc. I also seperated the projects files and directories
into distro specific pieces, with only arch currently being supported
with the `arch` script. The plan is to add debian support next with a
`debian` script and DebianLibraries directory. This all means the
Arch-Setup project name will probably change to support any Linux
distro.

diff --git a/Configurations/bashrc_extension b/Configurations/bashrc_extension
--- a/Configurations/bashrc_extension
+++ b/Configurations/bashrc_extension
@@ -28,7 +28,6 @@
     export TERM=xterm-256color
 }
 
-
 export PAGER="bat --paging=always --style=plain"
 export EDITOR=nvim
 alias e=$EDITOR
@@ -42,12 +41,7 @@ export HISTSIZE=10000
 alias ehist='history -a;eval "$(hist_fzf)"'
 alias hist="history -a;hist_fzf"
 
-alias up='ping quad9.net -c 4'
 alias newsboat='newsboat -c ~/.config/newsboat/cache.db'
-alias dlynx="lynx -cfg=$HOME/.config/lynx/lynx.cfg"
-
-alias sroot="sudo snapper -c root"
-alias shome="sudo snapper -c home"
 
 alias mf="man \$(ls /usr/share/man/man1 | awk -F. '{print \$1}' | fzf --reverse) 2>/dev/null"
 
@@ -60,55 +54,14 @@ then
     export BROWSER=qutebrowser
 fi
 
-
-if which bemenu &>/dev/null; then
-    alias bemenu-run="bemenu-run --fn 'monospace [14]' -w"
-    alias bemenu="bemenu --fn 'monospace [14]' -w"
-fi
-
-
-if [[ -n "$WAYLAND_DISPLAY" ]]; then
-    if which wlr-randr &>/dev/null
-    then
-        alias laptop_display=disconnect-external-displays
-        alias office_monitor=external_display_only
-        alias 2monitors="wlr-randr --output eDP-1 --off --output DP-10 --on --pos 2256,0 --output DP-9 --on --pos 4176,0"
-        alias 3monitors="wlr-randr --output eDP-1 --on --pos 0,0 --output DP-10 --on --pos 2256,0 --output DP-9 --on --pos 4176,0"
-        
-        if uname -r | grep "pinetab2" &>/dev/null
-        then
-            if wlr-randr | grep "HDMI-A-1" &>/dev/null; then
-                alias 1monitor="wlr-randr --output DSI-1 --off --output HDMI-A-1 --on --pos 0,0"
-                alias 2monitors="wlr-randr --output DSI-1 --on --transform 270 --pos 0,1280 --output HDMI-A-1 --on --pos 0,0"
-                alias 2monitors_other="wlr-randr --output DSI-1 --on --transform 270 --pos 0,1075 --output HDMI-A-1 --on --pos 1280,0"
-        fi
-    fi
-fi
-
-elif which dwm &>/dev/null; then
-    main_monitor="eDP-1"
-    middle_monitor="DP-2-2"
-    right_monitor="DP-2-1"
-    home_monitor="DP-2-2"
-
-    alias 3monitors="set-monitors $main_monitor $middle_monitor $right_monitor"
-    alias 2monitors="set-monitors $middle_monitor $right_monitor;xrandr --output $main_monitor --off"
-    alias 1monitor="set-monitors $main_monitor;xrandr --output $middle_monitor --off --output $right_monitor --off --output $home_monitor --off"
-
-    alias 2home_monitors="set-monitors $main_monitor $home_monitor"
-    alias 1home_monitor="set-monitors $home_monitor; xrandr --output $main_monitor --off"
-fi
-
-
-
 # pacman/yay + fzf
-if which pacman &>/dev/null; then
+if command -v pacman &>/dev/null; then
     # Package list : list all installed packages
     alias pl="pacman -Qq | fzf --preview 'pacman -Qi {}' --layout=reverse --preview-window '70%'"
     # Package search (find) : list all packages   ( 'ps' is taken by system utility )
     alias pf="pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse --preview-window '70%'"
 fi
-if which yay &>/dev/null; then
+if command -v yay &>/dev/null; then
     # Package list : list all installed packages
     alias yl="yay -Qq | fzf --preview 'yay -Qi {}' --layout=reverse --preview-window '70%'"
     # Package search (find) : list all packages
@@ -117,18 +70,22 @@ fi
 
 # Saves any running VirtualMachines before shutting down
 safe_shutdown() {
-    { which calcurse || type calcurse; } &>/dev/null && {
-        [[ -f $HOME/.local/share/calcurse/.calcurse.pid ]] && {
-            echo "You need to quit calcurse first.">&2
-            return 1
-        }
-    }
-
-    if { which virsh || type virsh; } &>/dev/null
+    if command -v calcurse &>/dev/null
     then
-        { which vm || type vm; } &>/dev/null && {
+        if [[ -f $HOME/.local/share/calcurse/.calcurse.pid ]]
+        then
+            printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+                "You need to close calcurse first.">&2
+            return 1
+    fi
+    fi
+
+    if command -v virsh &>/dev/null
+    then
+        if command -v vm &>/dev/null
+        then
             vm save --all
-        }
+        fi
     fi
 
     return 0
@@ -137,12 +94,12 @@ safe_shutdown() {
 shutdown_wrapper() {
     safe_shutdown || return 1
 
+    echo ""
     # Gives the user so many seconds to cancel the shutdown 
     for i in {5..1}; do
-        echo -ne "\rShutting Down In: $i"
+        printf "\r%s \e[1;36m%s\e[0m" "Shutting Down In:" "$i"
         sleep 1
     done
-    echo -e "\n"
 
     shutdown $@ 
 }
@@ -152,12 +109,12 @@ alias shutdown=shutdown_wrapper
 reboot_wrapper() {
     safe_shutdown || return 1
 
-    # Gives the user so many seconds to cancel the shutdown 
+    echo ""
+    # Gives the user so many seconds to cancel the reboot 
     for i in {5..1}; do
-        echo -ne "\rRebooting In: $i"
+        printf "\r%s \e[1;36m%s\e[0m" "Rebooting In:" "$i"
         sleep 1
     done
-    echo -e "\n"
 
     reboot $@
 }
@@ -179,11 +136,6 @@ hist_fzf() {
     done | fzf --reverse)"
 }
 
-dump() {
-    mkdir -p $HOME/notes
-    $EDITOR $HOME/notes/Dump.md
-}
-
 wttr() {
     if [[ -n "$LOCATION" ]]
     then
@@ -192,12 +144,6 @@ wttr() {
         echo "Must set the \$LOCATION variable first!"
         return 1
     fi
-}
-
-htmd() {
-    { which html2text || type html2text; } &>/dev/null \
-        && bat --language=md <(html2text <(curl -L --silent "$1")) \
-        || exit 1
 }
 
 spell() {
@@ -276,105 +222,6 @@ view_plan() {
     else
         printf "\e[31m%s\e[0m" "File '$FILE_PATH' doesn't exist"
     fi
-}
-
-# sets wallpaper
-wp() {
-    new_wallpaper_file_path="$1"
-    wallpaper_file_path=$HOME/.wallpaper
-
-    if ! [[ -f "$new_wallpaper_file_path" ]]
-    then
-        echo "[ERROR] Specified wallpaper path doesn't exist"
-        return 1
-    fi
-
-    if [[ -n "$DISPLAY" && -z "$WAYLAND_DISPLAY" ]]
-    then
-        cp "$new_wallpaper_file_path" $wallpaper_file_path
-        feh --bg-scale $wallpaper_file_path
-    elif [[ -n "$WAYLAND_DISPLAY" ]]
-    then
-        cp "$new_wallpaper_file_path" $wallpaper_file_path
-
-        # Kill existing swaybg command
-        if [[ -f "/tmp/.swaybg_pid" ]];then
-            kill $(cat /tmp/.swaybg_pid)
-            rm /tmp/.swaybg_pid
-        fi
-
-        nohup swaybg --mode fill --image $wallpaper_file_path &>/dev/null & \
-            echo $! > /tmp/.swaybg_pid
-    else
-        echo "[ERROR] Need a graphical environment active to set wallpaper"
-        return 1
-    fi
-}
-
-wpf() {
-    [[ -z "$DISPLAY" && -z "$WAYLAND_DISPLAY" ]] && {
-        echo "[ERROR] Need a graphical environment active to set wallpaper"
-        return 1
-    }
-
-    WALLPAPER_DIRECTORY=$HOME/Pictures/Wallpapers
-    mkdir -p $WALLPAPER_DIRECTORY &>/dev/null
-
-    [[ -f "$HOME/.wallpaper" ]] && cp $HOME/.wallpaper $HOME/.old_wallpaper
-
-    if [[ -n "$WAYLAND_DISPLAY" ]]; then
-        new_wallpaper=$( \
-            find $WALLPAPER_DIRECTORY -type f \
-            | fzf --reverse\
-                --preview="swaybg --mode fill --image {}" \
-                --preview-window=0% \
-        )
-    elif which dwm &>/dev/null; then
-        new_wallpaper=$( \
-            find $WALLPAPER_DIRECTORY -type f \
-            | fzf --reverse\
-                --preview="feh --bg-scale {}" \
-                --preview-window=0% \
-        )
-    fi
-
-
-    if [[ -n "$new_wallpaper" ]]
-    then
-        wp $new_wallpaper
-    else
-        wp $HOME/.old_wallpaper
-    fi
-}
-
-presnap() {
-    description="$1"
-    configs=($(sudo snapper list-configs | awk 'NR>2 {print $1}'))
-    for config in ${configs[@]}
-    do
-        sudo snapper -c $config create -d "$description" -t pre
-    done
-}
-
-postsnap() {
-    description="$1"
-    configs=($(sudo snapper list-configs | awk 'NR>2 {print $1}'))
-    for config in ${configs[@]}
-    do
-        pre_number=$(sudo snapper -c $config list | grep "pre" | grep "$description" | awk '{print $1}')
-        sudo snapper -c $config create -d "$description" -t post --pre-number "$pre_number"
-    done
-}
-
-deletesnap() {
-    description="$1"
-    configs=($(sudo snapper list-configs | awk 'NR>2 {print $1}'))
-    for config in ${configs[@]}
-    do
-        pre_number=$(sudo snapper -c $config list | grep "pre" | grep "$description" | awk '{print $1}')
-        snap_number=$(sudo snapper -c $config list | grep "$pre_number" | grep "$description" | awk -F '|' '{print $1}')
-        sudo snapper -c $config delete $snap_number
-    done
 }
 
 batt() {
@@ -526,88 +373,6 @@ chat()
     ollama run $model
 
     cleanup
-}
-
-theme() {
-    if ! [ -d $HOME/themes ]
-    then
-        echo "No themes directory in $HOME"
-        return 1
-    fi
-
-
-    if { which river || type river; } &>/dev/null
-    then
-        chosen_theme=$(ls $HOME/themes/river | fzf --reverse)
-        cp $HOME/themes/river/$chosen_theme/foot.ini $HOME/.config/foot/foot.ini
-        cp $HOME/themes/river/$chosen_theme/creek.flags $HOME/.river_creek_theme \
-            && restart-creek
-        cp $HOME/themes/river/$chosen_theme/terminal_prompt_theme $HOME/.terminal_prompt_theme
-        wp $HOME/themes/river/$chosen_theme/wallpaper.*
-
-        if { which qutebrowser || type qutebrowser; } &>/dev/null
-        then
-            cp $HOME/themes/river/$chosen_theme/qutebrowser_config.py \
-                ~/.config/qutebrowser/config.py
-            qutebrowser :config-source
-        fi
-
-        clear
-        newgrp
-    fi
-}
-
-change_pkg_version() {
-    sudo -v
-
-    package_name="$(ls /var/cache/pacman/pkg/ | grep -v "zst.sig" | fzf -i)"
-
-    if [[ -n $package_name ]]
-    then
-        sudo pacman -U /var/cache/pacman/pkg/$package_name
-    fi
-}
-
-# Turn off laptop display and turn on external display
-external_display_only() {
-    if [[ -n "$WAYLAND_LAPTOP_DISPLAY_NAME" ]]
-    then
-        display_names=($(wlr-randr | grep -v "^[[:space:]]" | awk '{print $1}'))
-
-        if [[ "${#display_names[@]}" -gt 2 ]]
-        then
-            echo "Too many displays connected"
-            return 1
-        fi
-
-        if echo "${display_names[@]}" | grep "$WAYLAND_LAPTOP_DISPLAY_NAME" &>/dev/null
-        then
-            echo "Turn off all displays"
-            for display in ${display_names[@]}
-            do
-                wlr-randr --output $display --off
-            done
-            for display in ${display_names[@]}
-            do
-                if [[ "$display" != "$WAYLAND_LAPTOP_DISPLAY_NAME" ]]
-                then
-                    echo "Turn on external display: $display"
-                    wlr-randr \
-                        --output "$WAYLAND_LAPTOP_DISPLAY_NAME" --off \
-                        --output $display --on --pos 0,0 &>/dev/null
-                    if { which creek || type creek; } &>/dev/null
-                    then
-                        echo "Restart creek"
-                        restart-creek &>/dev/null
-                    fi
-                    return 0
-                fi
-            done
-        fi
-    else
-        echo "\$WAYLAND_LAPTOP_DISPLAY_NAME variable not set"
-        return 1
-    fi
 }
 
 update_arch_iso() {
diff --git a/arch b/arch
--- a/arch
+++ b/arch
@@ -16,16 +16,11 @@
 # You should have received a copy of the GNU Affero General Public License
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
-
 #
 # CLI tool to replace Arch-Setup and Arch-Configurations. It will
 #  make the process of installing software and having them automatically
 #  configured to my setup much easier.
 #
-
-# TODO: remove-setup, how to know whether to remove packages or not?
-#   - for example, if the user setups gaming, and flatpak is installed,
-#     how do I know they haven't started using flatpak now?
 
 PROJECT_NAME="Arch-Setup"
 SCRIPT_NAME="arch"
@@ -34,25 +29,25 @@ REQUIRED_PACKAGES=( \
     bash pacman \
     usermod gpasswd groups groupadd groupdel \
     grep cat \
-    rfkill command \
+    rfkill command uname \
 )
 
 INSTALLABLE_PACKAGES="\
     yay qutebrowser librewolf docker rust python flatpak \
 "
 SETUP_OPTIONS="\
+    base_packages host_packages \
     security user-scripts audio bluetooth \
-    river gnome dwm dwl \
-    gaming media qemu 3d-printing \
+    gnome gaming media qemu 3d-printing \
     embedded-rust rust-dioxus \
 "
 
-PACKAGE_INSTALLATION_LIBRARY=package_installation_library.sh
-SETUP_INSTALLATION_LIBRARY=setup_installation_library.sh
+PACKAGE_INSTALLATION_LIBRARY=./ArchLibraries/package_installation_library.sh
+SETUP_INSTALLATION_LIBRARY=./ArchLibraries/setup_installation_library.sh
 
-PRETTY_OUTPUT_LIBRARY=pretty_output_library.sh
+PRETTY_OUTPUT_LIBRARY=./GeneralLibraries/pretty_output_library.sh
 
-CONFIG_INSTALL_SCRIPT=install_configurations.sh
+CONFIG_INSTALL_SCRIPT=./install_configurations.sh
 
 if ! echo "$@" | grep "add-to-path" &>/dev/null
 then
@@ -170,19 +165,19 @@ add_to_path() {
 }
 
 check_library_files_exist() {
-    if ! [[ -f "./$PRETTY_OUTPUT_LIBRARY" ]]
+    if ! [[ -f "$PRETTY_OUTPUT_LIBRARY" ]]
     then
         printf "\n\e[31m%s\e[0m\n" \
             "[!] Missing pretty output script. Cannot Proceed"
         exit 4
     fi
-    if ! [[ -f "./$PACKAGE_INSTALLATION_LIBRARY" ]]
+    if ! [[ -f "$PACKAGE_INSTALLATION_LIBRARY" ]]
     then
         printf "\n\e[31m%s\e[0m\n" \
             "[!] Missing package installation scripts. Cannot Proceed"
         exit 4
     fi
-    if ! [[ -f "./$SETUP_INSTALLATION_LIBRARY" ]]
+    if ! [[ -f "$SETUP_INSTALLATION_LIBRARY" ]]
     then
         printf "\n\e[31m%s\e[0m\n" \
             "[!] Missing setup installation scripts. Cannot Proceed"
@@ -194,7 +189,7 @@ check_packages()
 {
     for tool in ${REQUIRED_PACKAGES[@]}
     do
-        if ! { which $tool || type $tool; } &>/dev/null
+        if ! command -v $tool &>/dev/null
         then
             printf "\n\e[31m%s\e[0m\n" "[!] Must install '$tool' for $SCRIPT_NAME to work"
             tools_not_installed=1
@@ -230,7 +225,7 @@ display_help() {
         "rust, docker, qutebrowser)"
     printf "\n%s %s" \
         "(\`setup\` is for set it and forget it defaults:" \
-        "security, river, bluetooth)"
+        "security, gnome, bluetooth)"
 
     printf "\n\nBase Flags:"
     printf "\n  %-20s %-1s" "--version" "Returns version information"
@@ -250,7 +245,7 @@ display_help() {
     printf "\n  \`$SCRIPT_NAME install qutebrowser\`"
     printf "\n  \`$SCRIPT_NAME install rust qemu docker\`"
     printf "\n  \`$SCRIPT_NAME uninstall qutebrowser\`"
-    printf "\n  \`$SCRIPT_NAME setup river bluetooth\`"
+    printf "\n  \`$SCRIPT_NAME setup base_packages gnome bluetooth\`"
     printf "\n  \`$SCRIPT_NAME setup security user-scripts\`"
     printf "\n  \`$SCRIPT_NAME remove-setup rust\`"
     printf "\n  \`$SCRIPT_NAME add-configs\`"
@@ -269,6 +264,7 @@ display_help() {
     printf "\n  %-3s %-1s" "7" \
         "Missing system file or directory required by '$SCRIPT_NAME'"
     printf "\n  %-3s %-1s" "8" "Command run from the wrong directory"
+    echo ""
 }
 
 install() {
@@ -308,6 +304,7 @@ install() {
         do
             echo "  - $package_name"
         done
+        echo ""
         
         if [[ -n $packages_to_install ]]
         then
@@ -343,11 +340,13 @@ install() {
     for package_name in ${packages_to_install[@]}
     do
         case $package_name in
+            
             "yay")
                 if ! install_yay
                 then
                     printf "\n\e[31m%s\e[0m\n" \
                         "[!] Failed to install yay"
+                    exit 1
                 fi
             ;;
             "qutebrowser")
@@ -355,6 +354,7 @@ install() {
                 then
                     printf "\n\e[31m%s\e[0m\n" \
                         "[!] Failed to install qutebrowser"
+                    exit 1
                 fi
             ;;
             "librewolf")
@@ -362,6 +362,7 @@ install() {
                 then
                     printf "\n\e[31m%s\e[0m\n" \
                         "[!] Failed to install librewolf"
+                    exit 1
                 fi
             ;;
             "docker")
@@ -369,6 +370,7 @@ install() {
                 then
                     printf "\n\e[31m%s\e[0m\n" \
                         "[!] Failed to install docker"
+                    exit 1
                 fi
             ;;
             "python")
@@ -376,6 +378,7 @@ install() {
                 then
                     printf "\n\e[31m%s\e[0m\n" \
                         "[!] Failed to install python"
+                    exit 1
                 fi
             ;;
             "rust")
@@ -383,6 +386,7 @@ install() {
                 then
                     printf "\n\e[31m%s\e[0m\n" \
                         "[!] Failed to install rust"
+                    exit 1
                 fi
             ;;
             "flatpak")
@@ -390,6 +394,7 @@ install() {
                 then
                     printf "\n\e[31m%s\e[0m\n" \
                         "[!] Failed to install flatpak"
+                    exit 1
                 fi
             ;;
             *)
@@ -400,6 +405,7 @@ install() {
             ;;
         esac
     done
+
 }
 
 uninstall() {
@@ -437,7 +443,7 @@ uninstall() {
         printf "\nInstalled Packages:\n"
         for package_name in $INSTALLABLE_PACKAGES
         do
-            if ! { which yay || type yay; } &>/dev/null
+            if ! command -v yay &>/dev/null
             then
                 if yay -Q $package_name &>/dev/null
                 then
@@ -450,6 +456,7 @@ uninstall() {
                 fi
             fi
         done
+        echo ""
         
         if [[ -n $packages_to_uninstall ]]
         then
@@ -472,7 +479,7 @@ uninstall() {
         fi
 
 
-        if ! { which yay || type yay; } &>/dev/null
+        if ! command -v yay &>/dev/null
         then
             if ! yay -Q $package_name &>/dev/null
             then
@@ -600,6 +607,7 @@ setup() {
         do
             echo "  - $setup_name"
         done
+        echo ""
 
         if [[ -n $setups_chosen ]]
         then
@@ -634,6 +642,22 @@ setup() {
     for setup_name in ${setups_chosen[@]}
     do
         case $setup_name in
+            "base_packages")
+                if ! setup_base_packages
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to setup base_packages"
+                    exit 1
+                fi
+            ;;
+            "host_packages")
+                if ! setup_host_packages
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to setup host_packages"
+                    exit 1
+                fi
+            ;;
             "user-scripts")
                 if ! setup_user_scripts
                 then
@@ -704,6 +728,13 @@ setup() {
                         "[!] Failed to setup: 3d-printing"
                 fi
             ;;
+            "gnome")
+                if ! setup_gnome
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to setup: gnome"
+                fi
+            ;;
             *)
                 printf "\e[31m%s %s\e[0m" \
                     "Chosen setups did not match setup case statement." \
@@ -758,6 +789,22 @@ remove_setup() {
     for setup_name in ${setups_chosen[@]}
     do
         case $setup_name in
+            "base_packages")
+                if ! remove_setup_base_packages
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to remove setup: base_packages"
+                    exit 1
+                fi
+            ;;
+            "host_packages")
+                if ! remove_setup_host_packages
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to remove setup: host_packages"
+                    exit 1
+                fi
+            ;;
             "user-scripts")
                 if ! remove_setup_user_scripts
                 then
@@ -828,6 +875,13 @@ remove_setup() {
                         "[!] Failed to remove setup: 3d-printing"
                 fi
             ;;
+            "gnome")
+                if ! remove_setup_gnome
+                then
+                    printf "\n\e[31m%s\e[0m\n" \
+                        "[!] Failed to remove setup: gnome"
+                fi
+            ;;
             *)
                 printf "\n\e[31m%s %s\e[0m\n" \
                     "[!] Chosen setup did not match remove setup case statement." \
@@ -848,18 +902,33 @@ check_packages
 check_library_files_exist
 
 case $1 in
-    "install")             install ${@:2};bash ./$CONFIG_INSTALL_SCRIPT;;
-    "uninstall")           uninstall ${@:2};bash ./$CONFIG_INSTALL_SCRIPT;;
-    "setup")               setup ${@:2};bash ./$CONFIG_INSTALL_SCRIPT;;
-    "remove-setup")        remove_setup ${@:2};bash ./$CONFIG_INSTALL_SCRIPT;;
-    "add-configs")         bash ./$CONFIG_INSTALL_SCRIPT;;
+    "install")
+        install ${@:2}
+        cd $arch_setup_directory
+        bash $CONFIG_INSTALL_SCRIPT
+    ;;
+    "uninstall")
+        uninstall ${@:2}
+        cd $arch_setup_directory
+        bash $CONFIG_INSTALL_SCRIPT
+    ;;
+    "setup")
+        setup ${@:2}
+        cd $arch_setup_directory
+        bash $CONFIG_INSTALL_SCRIPT
+    ;;
+    "remove-setup")
+        remove_setup ${@:2}
+        cd $arch_setup_directory
+        bash $CONFIG_INSTALL_SCRIPT
+    ;;
+    "add-configs")         bash $CONFIG_INSTALL_SCRIPT;;
     "version"|"--version") echo "0.1.0";;
     "--help"|"-h") display_help;;
     *) 
-        printf "\n\n - [ERROR] Invalid use of the \`$SCRIPT_NAME\` command -";
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Invalid use of the \`$SCRIPT_NAME\` command"
         display_help
         exit 1
         ;;
 esac
-
-
