mpv_lynx improvements & rename. New move script.
Renamed mpv_lynx to min_browser as it had outgrown just using mpv and
lynx for opening links. Just started working on a new `move` script as a
more dynamic alternative to my static pack and unpack scripts.

diff --git a/DoNotRun/scripts/general_scripts/min_browser b/DoNotRun/scripts/general_scripts/min_browser
--- a/DoNotRun/scripts/general_scripts/min_browser
+++ b/DoNotRun/scripts/general_scripts/min_browser
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# mpv_lynx - part of the Arch-Setup project
+# min_browser - part of the Arch-Setup project
 # Copyright (C) 2023, Scott Wyman, development@scottwyman.me
 #
 # This program is free software: you can redistribute it and/or modify
@@ -24,22 +24,39 @@ URL="$1"
 
 VIDEO_URLS=("youtube.com" "odysee.com" "mp4")
 AUDIO_URLS=("mp3")
+IMAGE_URLS=("jpeg" "jpg" "png")
 
-# Loop through possible video url strings
+# Loop through possible video URLs
 for item in "${AUDIO_URLS[@]}"; do
     [[ $URL =~ $item ]] && { 
-        st -e mpv --no-video "$URL" 
-        exit
+        { (which st || type st) && [[ -n $DISPLAY ]]; } &>/dev/null \
+            && { st -e mpv --no-video "$URL"; exit; }  
     }
 done
 
-# Loop through possible video url strings
+# Loop through possible video URLs
 for item in "${VIDEO_URLS[@]}"; do
     [[ $URL =~ $item ]] && { 
-        mpv "$URL" > /dev/null 2>&1 
-        exit
+        { which mpv || type mpv; } &>/dev/null \
+            && { mpv "$URL" &>/dev/null; exit; }
     }
 done
 
-# Only open URL with lynx if lynx is installed
-which lynx &>/dev/null && lynx $URL
+# Loop through possible image URLs
+for item in "${IMAGE_URLS[@]}"; do
+    [[ $URL =~ $item ]] && { 
+        { which feh || type feh; } &>/dev/null \
+            && { feh "$URL" &>/dev/null; exit; }
+        
+        { which mpv || type mpv; } &>/dev/null \
+            && { mpv "$URL" &>/dev/null; exit; }
+
+    }
+done
+
+# Open url with lynx or python-html2text if all the loops failed
+{ which lynx || type lynx; } &>/dev/null && lynx $URL || {
+    { which html2text || type html2text; } &>/dev/null && {
+        bat --language=md <(html2text <(curl -L --silent "$URL"))
+    }
+}
