Integrated back in 'if' statements
I hadn't realized before that chaining many '&&' and '||' could cause
unintended behavior if any logic throughout the chain returns a non-zero
value... so I replaced all possibly problematic areas with if
statements.

diff --git a/DoNotRun/scripts/general_scripts/move b/DoNotRun/scripts/general_scripts/move
--- a/DoNotRun/scripts/general_scripts/move
+++ b/DoNotRun/scripts/general_scripts/move
@@ -22,7 +22,7 @@
 
 
 DATA_DIRECTORY=$HOME/.config/move
-BACKUP_PATHS=$DATA_DIRECTORY/backup_paths
+BACKUP_PATHS_FILE=$DATA_DIRECTORY/backup_paths
 
 [[ -d $DATA_DIRECTORY ]] || {
     echo -e "\n - [ERROR] $DATA_DIRECTORY doesn't exist... creating & exiting - \n"
@@ -30,116 +30,148 @@ BACKUP_PATHS=$DATA_DIRECTORY/backup_paths
     exit 1
 }
 
-{
-    compress() {
-        [[ -f $BACKUP_PATHS ]] && {
-            source $BACKUP_PATHS # imports the 'paths' array
 
-            cp /tmp/example.tar.aes.gz /tmp/example.tar.aes.gz.bak &>/dev/null
+display_help() {
+    echo -e "\nUsage: move [COMMAND]"
+    echo -e "\nA script for backing up and moving your important files"
 
-            # Verify all paths exist
-            for path in ${paths[@]};
-            do
-                [[ -d $path || -f $path ]] || {
-                    echo -e "\n - [ERROR] $path from $BACKUP_PATHS doesn't exist - \n"
-                    exit 1
-                }
-            done
+    echo "Commands:"
+    printf "\t%-15s %-1s\n" "list" "displays all files & directories to be backed up"
+    printf "\t%-15s %-1s\n" "pack" "'packs' all your files into a single directory or compressed file, ready for moving" 
+    printf "\t%-15s %-1s\n" "unpack" "'unpacks' all your files and places them around the system" 
+    printf "\t%-15s %-1s\n" "version" "Returns version information"
 
-            tar -czf /tmp/example.tar ${paths[@]}
-        }
-    }
+    echo -e "\nCommand Flags:\n"
+    echo -e "\tlist:"
+    printf "\t    %-20s\t %-1s\n" "-c | --custom-apps" "Display file and directories to be backed up for all supported custom apps"
+    printf "\t    %-20s\t %-1s\n" "-a | --all" "Display "
+    echo -e "\tpack:"
+    printf "\t    %-20s\t %-1s\n" "-c | --compress" "Compress all your files & directories into a single tar file"
+    printf "\t    %-20s\t %-1s\n" "-e | --encrypt" "Automatically encrypt the compressed backup file (must also pass the compress flag)"
+    printf "\t    %-20s\t %-1s\n" "-C | --clean" "Deletes the original tar file after encryption, keeping only the encrypt tar file (must also pass the compress flag)"
+    echo -e "\tunpack:"
+    printf "\t    %-20s\t %-1s\n" "-y | --noconfirm" "skip the 'are you sure' prompt"
+    printf "\t    %-20s\t %-1s\n" "--undo" "quickly undo the changes made by the last unpack command"
+    
+    echo -e "\nExamples:"
+    echo -e "\t\`move pack\`"
 
-    encrypt() {
-        while :
+    echo -e "\nError Codes:"
+    printf "\t%-3s %-1s\n" "1" "Invalid command"
+    printf "\t%-3s %-1s\n" "2" "Package doesn't exist"
+    printf "\t%-3s %-1s\n" "3" "Missing dependencies"
+
+    echo ""
+}
+
+
+compress() {
+    if [[ -f $BACKUP_PATHS_FILE ]]
+    then
+        source $BACKUP_PATHS_FILE # imports the 'paths' array
+
+        cp /tmp/example.tar.aes.gz /tmp/example.tar.aes.gz.bak &>/dev/null
+
+        # Verify all paths exist
+        for path in ${paths[@]};
         do
-            openssl enc \
-                -a -aes-256-cbc -pbkdf2 --iter 1000000 \
-                -in host_backup.tar -out host_backup.tar.aes 2> /dev/null
-
-            # Only exit the loop if the encryption succeeds
-            [[ $? == 0 ]] \
-                && break \
-                || echo -e "\n - Encryption keys don't match... try again - \n"
+            [[ -d $path || -f $path ]] || {
+                echo -e "\n - [ERROR] $path from $BACKUP_PATHS_FILE doesn't exist - \n"
+                exit 1
+            }
         done
-    }
 
-    pack() {
-        # unset flag variables before match, for safety
-        local unset skipped_command_input
+        tar -czf /tmp/example.tar ${paths[@]}
+    fi
+}
 
-        #
-        # Capture flags
-        #
-        for arg in "${@}";
-        do
-            case $arg in
-                "--noconfirm" | "-y")
-                    [[ -n "$noconfirm_flag" ]] && {
-                        echo -e "\n - [ERROR] duplicated the 'noconfirm' flag - \n"
-                        exit 1
-                    }
-                    local noconfirm_flag="--noconfirm"
-                ;;
-                *) 
-                    [[ "$arg" == "pack" && -z "$skipped_command_input" ]] && {
-                        skipped_command_input=true
-                        continue
-                    }
+encrypt() {
+    while :
+    do
+        openssl enc \
+            -a -aes-256-cbc -pbkdf2 --iter 1000000 \
+            -in host_backup.tar -out host_backup.tar.aes 2> /dev/null
 
-                    local package_names+=($arg)
-                ;;
-            esac
-        done
-    }
+        # Only exit the loop if the encryption succeeds
+        [[ $? == 0 ]] \
+            && break \
+            || echo -e "\n - Encryption keys don't match... try again - \n"
+    done
+}
 
-
-    #
-    # If a supported app is installed, back it up
-    #
-    calurse_pack() {
-        { which calcurse || type calcurse; } &>/dev/null && {
-            [[ -d $HOME/.config/calcurse ]] && {
-
-        }
-    }
-
-    custom_app_pack() {
-        calurse_pack
+#
+# If a supported app is installed, back it up
+#
+calurse_pack() {
+    { which calcurse || type calcurse; } &>/dev/null && {
+        [[ -d $HOME/.config/calcurse ]] && {
+            echo "under construction"
     }
 }
 
-{
-    
+custom_app_pack() {
+    calurse_pack
+}
 
-    unpack() {
-        # unset flag variables before match, for safety
-        local unset skipped_command_input
+pack() {
+    # unset flag variables before match, for safety
+    local unset skipped_command_input
 
-        #
-        # Capture flags
-        #
-        for arg in "${@}";
-        do
-            case $arg in
-                "--noconfirm" | "-y")
-                    [[ -n "$noconfirm_flag" ]] && {
-                        echo -e "\n - [ERROR] duplicated the 'noconfirm' flag - \n"
-                        exit 1
-                    }
-                    local noconfirm_flag="--noconfirm"
-                ;;
-                *) 
-                    [[ "$arg" == "unpack" && -z "$skipped_command_input" ]] && {
-                        skipped_command_input=true
-                        continue
-                    }
+    #
+    # Capture flags
+    #
+    for arg in "${@}";
+    do
+        case $arg in
+            "--noconfirm" | "-y")
+                [[ -n "$noconfirm_flag" ]] && {
+                    echo -e "\n - [ERROR] duplicated the 'noconfirm' flag - \n"
+                    exit 1
+                }
+                local noconfirm_flag="--noconfirm"
+            ;;
+            *) 
+                [[ "$arg" == "pack" && -z "$skipped_command_input" ]] && {
+                    skipped_command_input=true
+                    continue
+                }
 
-                    local package_names+=($arg)
-                ;;
-            esac
-        done
-    }
+                local package_names+=($arg)
+            ;;
+        esac
+    done
+}
+
+
+
+
+unpack() {
+    # unset flag variables before match, for safety
+    local unset skipped_command_input
+
+    #
+    # Capture flags
+    #
+    for arg in "${@}";
+    do
+        case $arg in
+            "--noconfirm" | "-y")
+                [[ -n "$noconfirm_flag" ]] && {
+                    echo -e "\n - [ERROR] duplicated the 'noconfirm' flag - \n"
+                    exit 1
+                }
+                local noconfirm_flag="--noconfirm"
+            ;;
+            *) 
+                [[ "$arg" == "unpack" && -z "$skipped_command_input" ]] && {
+                    skipped_command_input=true
+                    continue
+                }
+
+                local package_names+=($arg)
+            ;;
+        esac
+    done
 }
 
 case $1 in
diff --git a/DoNotRun/scripts/general_scripts/ssh-swap b/DoNotRun/scripts/general_scripts/ssh-swap
--- a/DoNotRun/scripts/general_scripts/ssh-swap
+++ b/DoNotRun/scripts/general_scripts/ssh-swap
@@ -35,23 +35,31 @@ generate_ssh_key() {
 while :
     do
         read -p 'Enter a name for the keyfile: ' key_file
-        [[ -e ~/.ssh/$key_file ]] \
-            && echo -e "\n - keyfile already exists, try another name - \n" \
-            || {
-                ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$key_file" && {
-                    echo "SSH key pair generated."
-                    break
-                } || exit 1
-            }
+        if [[ -e ~/.ssh/$key_file ]]
+        then
+            echo -e "\n - keyfile already exists, try another name - \n"
+        else
+            if ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$key_file"
+            then
+                echo "SSH key pair generated."
+                break
+            else
+                exit 1
+            fi
+        fi
     done
 }
 
 # Swap SSH keys with the remote device
 swap_ssh_keys() {
-    ssh-copy-id -p $ssh_port -i ~/.ssh/"$key_file".pub "$username@$ip_address" && {
+    if ssh-copy-id -p $ssh_port -i ~/.ssh/"$key_file".pub "$username@$ip_address"
+    then
         echo "SSH keys swapped, use this command to connect: "
         echo "ssh -p $ssh_port -i ~/.ssh/$key_file $username@$ip_address"
-    } || { echo -e "\n - [ERROR] Failed to swap SSH keys - \n"; exit 1; } 
+    else
+        echo -e "\n - [ERROR] Failed to swap SSH keys - \n"
+        exit 1
+    fi
 }
 
 
diff --git a/DoNotRun/scripts/general_scripts/vm b/DoNotRun/scripts/general_scripts/vm
--- a/DoNotRun/scripts/general_scripts/vm
+++ b/DoNotRun/scripts/general_scripts/vm
@@ -150,17 +150,19 @@ open_vm() {
             exit 2
         } 
 
-        [[ "$open_in_console_flag" == "--console" ]] && {
+        if [[ "$open_in_console_flag" == "--console" ]]
+        then
             virsh console $vm_name
-            true
-        } || {
-            [[ -n "$virt_viewer_flag" ]] && {
+        else
+            if [[ -n "$virt_viewer_flag" ]]
+            then
                 nohup virt-viewer -a $fullscreen_virt_viewer_flag "$vm_name" \
                     &> /tmp/${vm_name}_virt_viewer.log &
                 echo "virt-viewer stdin and stdout will be written to /tmp/${vm_name}_virt_viewer.log"
-                true
-            } || virt-manager -c qemu:///session --show-domain-console "$vm_name"
-        }
+            else
+                virt-manager -c qemu:///session --show-domain-console "$vm_name"
+            fi
+        fi
     done
 }
 
@@ -217,14 +219,18 @@ save_vm() {
             exit 2
         }
 
-        [[ "${vm_states[$vm_name]}" == "running" || "${vm_states[$VM_NAME]}" == "paused" ]] && {
-            [[ $save_to_file_flag == true && -n "$file_path" ]] \
-                && { virsh save --verbose $vm_name $file_path; true; } \
-                || virsh managedsave --verbose $vm_name
-        } || { 
+        if [[ "${vm_states[$vm_name]}" == "running" || "${vm_states[$VM_NAME]}" == "paused" ]]
+        then
+            if [[ $save_to_file_flag == true && -n "$file_path" ]]
+            then 
+                virsh save --verbose $vm_name $file_path
+            else 
+                virsh managedsave --verbose $vm_name
+            fi
+        else
             echo -e "\n - [ERROR] Cannot save VM if it's not running or paused - \n"
             exit 1
-        }
+        fi
     done
 }
 
@@ -393,15 +399,16 @@ start_vm() {
 
     # file path is only used to restore from file, so no VM name is needed
     #  ! Subject to change to allow other flags
-    [[ -n "$file_path" && -f "$file_path" && -n "${vm_names[@]}" ]] || {
+    if [[ -n "$file_path" && -f "$file_path" && -n "${vm_names[@]}" ]]
+    then
+        echo -e "\n - [ERROR] file path - \n"
+        exit 1
+    else
         [[ $restore_from_file_flag == true && -n "$file_path" ]] && {
             virsh restore "$file_path"
             exit 0
         }
-    } && {
-        echo -e "\n - [ERROR] file path - \n"
-        exit 1
-    }
+    fi
 
     [[ -z ${vm_names[@]} ]] && {
         echo -e "\n - [ERROR] must pass at least one VM name - \n"
@@ -414,14 +421,15 @@ start_vm() {
             exit 2
         }
 
-        [[ "${vm_states[$vm_name]}" = "saved" ]] && {
+        if [[ "${vm_states[$vm_name]}" = "saved" ]]
+        then
             virsh restore ~/.config/libvirt/qemu/save/$vm_name.save \
                 && virsh managedsave-remove "$vm_name" # Only remove if the restore works 
-        } || {
+        else
             [[ "${vm_states[$vm_name]}" = "off" ]] && virsh start "$vm_name" || {
                 echo "VM '$vm_name' already on...applying flags"
             }
-        }
+        fi
 
         #
         # Apply Flags
