More scripts, improved `vm`, other small changes.
Added more native-like app scripts for lynx and neomutt (like browser). Added
the option to open VMs serial console instead of their graphical environment
with the `vm` script. Improved ssh-swap logic.

diff --git a/DoNotRun/scripts/general_scripts/ssh-swap b/DoNotRun/scripts/general_scripts/ssh-swap
--- a/DoNotRun/scripts/general_scripts/ssh-swap
+++ b/DoNotRun/scripts/general_scripts/ssh-swap
@@ -17,60 +17,43 @@
 # along with this program.  If not, see <https://www.gnu.org/licenses/>.
 
 
-# Set the username and IP address of the remote Linux deviceecho -m "
-echo -n "Enter the remote username: "
-read USERNAME
-echo -n "Enter the remote IP Address: "
-read IP_ADDRESS
+mkdir -p $HOME/.ssh
 
-SSH_PORT=22
-echo -n "Enter SSH port if not 22: "
-read NEW_SSH_PORT
-# If the user entered a port, use that instead
-[[ -n NEW_SSH_PORT ]] && SSH_PORT=$NEW_SSH_PORT
+# Set the username and IP address of the remote Linux deviceecho -m "
+read -p 'Enter the remote username: ' username
+read -p 'Enter the remote IP Address: ' ip_address
+read -p 'Enter SSH port if not 22: ' ssh_port
+[[ -z "$ssh_port" ]] && ssh_port=22 
+
+[[ -z "$username" || -z "$ip_address" || -z "$ssh_port" ]] && {
+    echo -e "\n - [ERROR] Must provide a valid username, IP address, and port number - \n"
+    exit 1
+}
 
 # Generate a new SSH key pair
 generate_ssh_key() {
 while :
     do
-        echo -n "Enter a random keyfile name: "
-        read KEY_FILE
-        if [[ -e ~/.ssh/$KEY_FILE ]]; then
-            ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$KEY_FILE"
-            
-            if [[ $? == 0 ]];then
-                echo "SSH key pair generated."
-                break
-            # Returns 1 if the keyfile already exists. Loops so the
-            #   user can choose a new filename
-            else
-                clear
-            fi
-
-        else
-            ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$KEY_FILE"
-            echo "SSH key pair generated."
-            break
-        fi
+        read -p 'Enter a name for the keyfile: ' key_file
+        [[ -e ~/.ssh/$key_file ]] \
+            && echo -e "\n - keyfile already exists, try another name - \n" \
+            || {
+                ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$key_file" && {
+                    echo "SSH key pair generated."
+                    break
+                } || exit 1
+            }
     done
 }
 
 # Swap SSH keys with the remote device
 swap_ssh_keys() {
-    ssh-copy-id -p $SSH_PORT -i ~/.ssh/"$KEY_FILE".pub "$USERNAME@$IP_ADDRESS"
-    # if the command is successful
-    if [[ $? == 0 ]];
-    then
+    ssh-copy-id -p $ssh_port -i ~/.ssh/"$key_file".pub "$username@$ip_address" && {
         echo "SSH keys swapped, use this command to connect: "
-        echo "ssh -p $SSH_PORT -i ~/.ssh/$KEY_FILE $USERNAME@$IP_ADDRESS"
-    else
-        echo "Failed to swap SSH keys" 
-    fi 
+        echo "ssh -p $ssh_port -i ~/.ssh/$key_file $username@$ip_address"
+    } || { echo -e "\n - [ERROR] Failed to swap SSH keys - \n"; exit 1; } 
 }
 
-main() {
-    generate_ssh_key
-    swap_ssh_keys
-}
 
-main
+generate_ssh_key
+swap_ssh_keys
diff --git a/DoNotRun/scripts/general_scripts/vm b/DoNotRun/scripts/general_scripts/vm
--- a/DoNotRun/scripts/general_scripts/vm
+++ b/DoNotRun/scripts/general_scripts/vm
@@ -72,14 +72,37 @@ open_vm() {
     unset fullscreen_virt_viewer_flag \
         virt_viewer_flag \
         vm_names \
-        skipped_command_input
+        skipped_command_input \
+        open_in_console_flag
+
     #
     # Capture flags
     #
     for arg in "${@}";
     do
         case $arg in
+            "--console" | "-c")
+                [[ -n "$virt_viewer_flag" ]] && {
+                    echo -e "\n - [ERROR] Cannot pass the virt-viewer and console flags together - \n"
+                    exit 1
+                }
+                [[ -n "$fullscreen_virt_viewer_flag" ]] && {
+                    echo -e "\n - [ERROR] Cannot pass the fullscreen and console flags together - \n"
+                    exit 1
+                }
+
+                [[ -n "$open_in_console_flag" ]] && {
+                    echo -e "\n - [ERROR] duplicated console flag - \n"
+                    exit 1
+                }
+                open_in_console_flag="--console"
+            ;;
             "--virt-viewer" | "-V")
+                [[ -n "$open_in_console_flag" ]] && {
+                    echo -e "\n - [ERROR] Cannot pass the virt-viewer and console flags together - \n"
+                    exit 1
+                }
+
                 [[ -n "$virt_viewer_flag" ]] && {
                     echo -e "\n - [ERROR] duplicated virt-viewer flag - \n"
                     exit 1
@@ -90,6 +113,11 @@ open_vm() {
                     || { echo -e "\n - [ ERROR ] virt-viewer not installed - \n"; exit 3; } 
             ;;
             "--fullscreen" | "-f")
+                [[ -n "$open_in_console_flag" ]] && {
+                    echo -e "\n - [ERROR] Cannot pass the fullscreen and console flags together - \n"
+                    exit 1
+                }
+
                 [[ -n "$fullscreen_virt_viewer_flag" ]] && {
                     echo -e "\n - [ERROR] duplicated fullscreen flag - \n"
                     exit 1
@@ -122,11 +150,15 @@ open_vm() {
             exit 2
         } 
 
-        [[ -n "$virt_viewer_flag" ]] && {
-            nohup virt-viewer -a $fullscreen_virt_viewer_flag "$vm_name" \
-                &> /tmp/${vm_name}_virt_viewer.log &
-            echo "virt-viewer stdin and stdout will be written to /tmp/${vm_name}_virt_viewer.log"
-        } || virt-manager -c qemu:///session --show-domain-console "$vm_name"
+        [[ "$open_in_console_flag" == "--console" ]] && {
+            virsh console $vm_name
+        } || {
+            [[ -n "$virt_viewer_flag" ]] && {
+                nohup virt-viewer -a $fullscreen_virt_viewer_flag "$vm_name" \
+                    &> /tmp/${vm_name}_virt_viewer.log &
+                echo "virt-viewer stdin and stdout will be written to /tmp/${vm_name}_virt_viewer.log"
+            } || virt-manager -c qemu:///session --show-domain-console "$vm_name"
+        }
     done
 }
 
@@ -211,25 +243,28 @@ display_help() {
     echo -e "\nCommand Flags:\n"
     echo -e "\tstart:"
     printf "\t    %-20s\t %-1s\n" "-o | --open" "Open the VM with virt-manager"
-    printf "\t    %-20s\t %-1s\n" "-V | --virt-viewer" "If the open flag is passed, open with virt-viewer instead of virt-manager"
-    printf "\t    %-20s\t %-1s\n" "-f | --fullscreen" "If the open flag is passed, and virt-viewer is being used, open in fullscreen"
+    printf "\t    %-20s\t %-1s\n" "-V | --virt-viewer" "Open the VM with virt-viewer instead of virt-manager"
+    printf "\t    %-20s\t %-1s\n" "-f | --fullscreen" "Pass with the virt-viewer flag to open in fullscreen"
+    printf "\t    %-20s\t %-1s\n" "-c | --console" "Open the VMs serial console in your terminal."
     printf "\t    %-20s\t %-1s\n" "-F | --file" "Restore VM from a manually saved VM state file. Only the file name with no additional flags should be passed."
     echo -e "\topen:"
     printf "\t    %-20s\t %-1s\n" "-V | --virt-viewer" "Open with virt-viewer instead of virt-manager"
-    printf "\t    %-20s\t %-1s\n" "-f | --fullscreen" "If using virt-viewer, open in fullscreen"
+    printf "\t    %-20s\t %-1s\n" "-f | --fullscreen" "Pass with the virt-viewer flag to open in fullscreen"
+    printf "\t    %-20s\t %-1s\n" "-c | --console" "Open the VMs serial console in your terminal."
     echo -e "\tsave:"
     printf "\t    %-20s\t %-1s\n" "-F | --file" "Manually save VM state to a file. Only the VM name and location should be passed with no additional flags."
 
     echo -e "\nExamples:"
     echo -e "\t\`vm list\`"
-    echo -e "\t\`vm start <vm_name1> <vm_name2>\`"
-    echo -e "\t\`vm start --open --virt-viewer <vm_name1> <vm_name2>\`"
-    echo -e "\t\`vm start -o -V <vm_name1>\`"
-    echo -e "\t\`vm start -f </some/path/vm_save_file.save>\`"
-    echo -e "\t\`vm open -V <vm_name1> <vm_name2>\`"
-    echo -e "\t\`vm save <vm_name1>\`"
-    echo -e "\t\`vm save <vm_name1> -f </some/path/vm_save_file.save>\`"
-    echo -e "\t\`vm is-running <vm_name1> <vm_name2> && echo 'running!'\`"
+    echo -e "\t\`vm start --open <vm_name1> <vm_name2>\`"
+    echo -e "\t\`vm start -c <vm_name>\`"
+    echo -e "\t\`vm start --virt-viewer <vm_name1> <vm_name2>\`"
+    echo -e "\t\`vm start -V <vm_name1>\`"
+    echo -e "\t\`vm start --file </some/path/vm_save_file.save>\`"
+    echo -e "\t\`vm open -V -f <vm_name1> <vm_name2>\`"
+    echo -e "\t\`vm save <vm_name1>\`                                   # Will be managed by virsh"
+    echo -e "\t\`vm save <vm_name1> -f </some/path/vm_save_file.save>\` # Manage on your own"
+    echo -e "\t\`vm is-running <vm_name1> <vm_name2> && echo 'all VMs running!'\`"
 
     echo -e "\nError Codes:"
     printf "\t%-3s %-1s\n" "1" "Invalid command (also used to indicate VM not running for the \`is-running\` command."
@@ -275,7 +310,8 @@ start_vm() {
         vm_names \
         skipped_command_input \
         restore_from_file_flag \
-        file_path
+        file_path \
+        open_in_console_flag
     #
     # Capture flags
     #
@@ -290,11 +326,28 @@ start_vm() {
                 restore_from_file_flag=true
             ;;
             "--open" | "-o")
+                [[ -n "$open_in_console_flag" ]] && {
+                    echo -e "\n - [ERROR] Cannot pass the open and console flags together - \n"
+                    exit 1
+                }
+
                 [[ -n "$open_flag" ]] && {
                     echo -e "\n - [ERROR] duplicated open flag - \n"
                     exit 1
                 }
                 open_flag=true
+            ;;
+            "--console" | "-c")
+                [[ -n "$open_flag" ]] && {
+                    echo -e "\n - [ERROR] Cannot pass the open and console flags together - \n"
+                    exit 1
+                }
+
+                [[ -n "$open_in_console_flag" ]] && {
+                    echo -e "\n - [ERROR] duplicated console flag - \n"
+                    exit 1
+                }
+                open_in_console_flag="--console"
             ;;
             "--virt-viewer" | "-V")
                 [[ -n "$virt_viewer_flag" ]] && {
@@ -302,28 +355,25 @@ start_vm() {
                     exit 1
                 }
 
-                [[ -z "$open_flag" ]] && { 
-                    echo -e "\n - [ERROR] must pass open flag to use virt-viewer - \n"
-                    exit 1
-                }
-
                 virt-viewer --version &>/dev/null \
                     && virt_viewer_flag='-V' \
                     || { echo -e "\n - [ERROR] virt-viewer not installed - \n"; exit 3; } 
+
+                open_flag=true
             ;;
             "--fullscreen" | "-f")
                 [[ -n "$fullscreen_virt_viewer_flag" ]] && {
                     echo -e "\n - [ERROR] duplicated fullscreen flag - \n"
                     exit 1
                 }
-                [[ -n "$virt_viewer_flag" && -n "$open_flag" ]] \
+                [[ -n "$virt_viewer_flag" ]] \
                     && fullscreen_virt_viewer_flag="-f" \
                     || { 
                         echo -e "\n - [ERROR] full screen requires the virt-viewer and open flags - \n"
                         exit 1
                     } 
             ;;
-            *) 
+            *)
                 [[ "$arg" == "start" && -z "$skipped_command_input" ]] && {
                     skipped_command_input=true
                     continue
@@ -367,8 +417,7 @@ start_vm() {
                 && virsh managedsave-remove "$vm_name" # Only remove if the restore works 
         } || {
             [[ "${vm_states[$vm_name]}" = "off" ]] && virsh start "$vm_name" || {
-                echo -e "\n - [ERROR] VM not in an off or saved state, so it cannot be started - \n"
-                exit 1
+                echo "VM '$vm_name' already on...applying flags"
             }
         }
 
@@ -377,6 +426,8 @@ start_vm() {
         #
         [[ $open_flag == true ]] \
             && open_vm $virt_viewer_flag $fullscreen_virt_viewer_flag $vm_name
+        [[ "$open_in_console_flag" == "--console" ]] \
+            && open_vm $open_in_console_flag $vm_name
     done
 }
 
