Update move, notes, and store
  * Use age instead of openssl
  * Seperate encryption and decryption into reusable functions
  * Use printf instead of echo
  * Shorten and improve much of the old logic

diff --git a/ScriptsAddedToPath/notes b/ScriptsAddedToPath/notes
--- a/ScriptsAddedToPath/notes
+++ b/ScriptsAddedToPath/notes
@@ -18,153 +18,194 @@
 
 PACKED_NOTES_BASENAME="packed_notes"
 
-ensure_notes_dir() {
-    if [[ -d $HOME/notes ]]
-    then
-        return 0
-    else
-        echo "A 'notes' directory must be placed in your home directory, exiting..."
-        return 1
-    fi
-}
+REQUIRED_COMMANDS=(printf age tar gzip gunzip)
 
-pack() {
-    #
-    # Capture flags
-    #
-    for arg in "${@}";
+ensure_commands_installed()
+{
+    for cmd in ${REQUIRED_COMMANDS[@]}
     do
-        case $arg in
-            "--clean" | "-c")
-                [[ -z $clean_flag ]] && {
-                    clean_flag=true
-                }
-            ;;
-            *)
-                [[ "$arg" == "pack" && -z "$skipped_command_input" ]] && {
-                    skipped_command_input=true
-                    continue
-                }
-            ;;
-        esac
-    done
-
-    ORIGINAL_PWD=$PWD
-    cd $HOME
-    echo "Compressing Notes..."
-    tar -czf $PACKED_NOTES_BASENAME.tar.gz notes
-
-    mv $PACKED_NOTES_BASENAME.tar.gz $ORIGINAL_PWD/ &>/dev/null
-    cd $ORIGINAL_PWD
-
-    echo "Encrypting Notes..."
-
-    while :
-    do
-        # Encrypt the backup for transport
-        if openssl enc -a -aes-256-cbc -pbkdf2 --iter 1000000 \
-            -in $PACKED_NOTES_BASENAME.tar.gz \
-            -out $PACKED_NOTES_BASENAME.tar.gz.aes 2> /dev/null
+        if ! command -v $cmd &>/dev/null
         then
-            good_encryption=true
-            break
-        else
-            echo -e "\n - Encryption keys don't match... try again - \n"
+            printf "\n\n\e[31m%s %s\e[0m\n\n" \
+                "[!] Missing required command: '$cmd'."
+            return 1
         fi
     done
 
-    # Remove the unencrypted .tar.gz file
-    shred -uz $PACKED_NOTES_BASENAME.tar.gz
-
-    if [[ $good_encryption == true ]]
-    then
-        #
-        # Apply Flags
-        #
-        [[ $clean_flag == true ]] && rm -rf $HOME/notes 
-
-        echo "Notes packed to '$PACKED_NOTES_BASENAME.tar.gz.aes'"
-        return 0
-    else
-        echo "Had and issue encrypting '$PACKED_NOTES_BASENAME.tar.gz'"
-        return 1
-    fi
+    return 0
 }
 
-unpack() {
-    if ! [[ -f $PACKED_NOTES_BASENAME.tar.gz.aes ]]
+ensure_commands_installed || exit $?
+
+ensure_notes_dir() {
+    if [[ -d "${HOME}/notes" ]]
     then
-        echo "No '$PACKED_NOTES_BASENAME.tar.gz.aes' file found, exiting..."
-        return 1
-    fi
-
-    if [[ -d $HOME/notes ]]
-    then
-        read -p "'$HOME/notes' already exists, are you sure you want to overwrite it? [y/N]: " overwrite_notes
-        [[ $overwrite_notes == "y" || $overwrite_notes == "Y" || $overwrite_notes == "yes" ]] || {
-            echo "Skipping unpack..."
-            return 1
-        }
-    fi
-
-    echo "Decrypting Notes..."
-    while :
-    do
-        # Decrypt the backup
-        openssl enc -d -a -aes-256-cbc -pbkdf2 --iter 1000000 \
-            -in $PACKED_NOTES_BASENAME.tar.gz.aes \
-            -out $PACKED_NOTES_BASENAME.tar.gz 2> /dev/null
-
-        # Test if the file was decrypted correctly
-        tar --list --file $PACKED_NOTES_BASENAME.tar.gz &>/dev/null \
-            && break \
-            || echo -e "\n - Incorrect decryption key... try again - \n"
-    done
-
-    mv $PACKED_NOTES_BASENAME.tar.gz $HOME/ &>/dev/null
-    cd $HOME
-
-    if tar -xf $PACKED_NOTES_BASENAME.tar.gz &>/dev/null
-    then
-        shred -uz $PACKED_NOTES_BASENAME.tar.gz
-        echo "Notes unpacked!"
         return 0
     else
-        echo "[ERROR] Failed to decompress the unencrypted '$PACKED_NOTES_BASENAME.tar.gz' file"
-        return 1
-    fi
-}
-
-open_notes() {
-    if { which lf || type lf; } &>/dev/null
-    then
-        lf $HOME/notes
-    else
-        echo -e "\n - [ERROR] Must have 'lf' installed to traverse notes - \n"
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "'${HOME}/notes' directory must exist. Stopping."
         return 1
     fi
 }
 
 display_help() {
-    echo -e "\nUsage: notes [COMMAND]"
-    echo -e "\nEasy management of encrypted notes in the terminal. Uses \`lf\` for note traversal"
+    printf "\nUsage: notes [COMMAND]"
+    printf "\n%s %s\n" \
+        "Easy management of encrypted notes in the terminal. Uses \`lf\`" \
+        "for note traversal"
 
-    echo -e "\nCommands:"
-    printf "\t%-10s %-10s\n" "pack" "Compress and encrypt '\$HOME/notes' into a packed_notes.tar.gz.aes file"
-    printf "\t%-10s %-10s\n" "unpack" "Decrypt and decompress packed_notes.tar.gz.aes into the '\$HOME/notes' directory"
+    printf "\nCommands:"
+    printf "\n  %-12s %s" "pack" \
+        "Compress and encrypt '\$HOME/notes' into a packed_notes.tar.gz.age file"
+    printf "\n  %-12s %s" "unpack" \
+        "Decrypt and decompress packed_notes.tar.gz.age into the '\$HOME/notes' directory"
 
-    echo -e "\nCommand Flags:\n"
-    echo -e "\tpack:"
-    printf "\t    %-10s\t %-1s\n" "--clean" "removes '\$HOME/notes' after creating packed_notes.tar.gz.aes"
-
-    echo -e "\nExamples:"
-    echo -e "\t\`notes\` # opens notes in lf"
-    echo -e "\t\`notes pack\`"
-    echo -e "\t\`notes pack --clean\`"
-    echo -e "\t\`notes unpack\`"
-
-    echo ""
+    printf "\n\nExamples:"
+    printf "\n  \`notes\` # opens notes in lf"
+    printf "\n  \`notes pack\`"
+    printf "\n  \`notes unpack\`\n"
 }
+
+encrypt()
+{
+    filename="$1"
+
+    for attempt in {1..5}
+    do
+        if [[ $attempt -ne 1 ]]
+        then
+            printf "\n%s \e[36m%s\e[0m %s\n" "Attempt" "$attempt" "of 5"
+        fi
+
+        age --passphrase "${filename}.tar.gz" > "${filename}.tar.gz.age"
+
+        if [[ $? == 0 ]]
+        then
+            return 0
+        else
+            printf "\n\n\e[31m%s\e[0m %s\n\n" "[Error]" \
+                "Encryption failed... try again"
+        fi
+    done
+
+    return 1
+}
+
+pack() {
+    if [[ -f "${PACKED_NOTES_BASENAME}.tar.gz.age" ]] \
+    then
+        cp "${PACKED_NOTES_BASENAME}.tar.gz.age" \
+            "${PACKED_NOTES_BASENAME}.tar.gz.age.bak" &>/dev/null
+    fi
+
+    printf "\n\e[36m%s\e[0m %s\n" "Compressing notes..."
+    if tar --create --gzip --directory="$HOME" \
+        --file="${PACKED_NOTES_BASENAME}.tar.gz" notes &>/dev/null
+    then
+        printf "\n\e[36m%s\e[0m %s\n" "Encrypt notes:"
+        if encrypt "${PACKED_NOTES_BASENAME}"
+        then
+            rm "${PACKED_NOTES_BASENAME}.tar.gz"
+            printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
+                "File packed to: ${PACKED_NOTES_BASENAME}.tar.gz.age"
+            return 0
+        else
+            printf "\n\e[31m%s\e[0m %s %s\n" "[Error]" \
+                "Couldn't encrypt compressed notes file:" \
+                "'${PACKED_NOTES_BASENAME}.tar.gz'"
+        fi
+    else
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Couldn't compress '${HOME}/notes' with tar. Stopping."
+        return 1
+    fi
+
+    if [[ -f "${PACKED_NOTES_BASENAME}.tar.gz.age.bak" ]]
+    then
+        cp "${PACKED_NOTES_BASENAME}.tar.gz.age.bak" \
+            "${PACKED_NOTES_BASENAME}.tar.gz.age" &>/dev/null
+    fi
+    return 0
+}
+
+decrypt()
+{
+    filename="$1"
+
+    for attempt in {1..5}
+    do
+        if [[ $attempt -ne 1 ]]
+        then
+            printf "\n%s \e[36m%s\e[0m %s\n" "Attempt" "$attempt" "of 5"
+        fi
+
+        age --decrypt "${filename}.tar.gz.age" > "${filename}.tar.gz"
+
+        if tar --list --file="${PACKED_NOTES_BASENAME}.tar.gz" &>/dev/null
+        then
+            return 0
+        else
+            printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+                "Incorrect decryption key... try again"
+        fi
+    done
+        
+    return 1
+}
+
+unpack() {
+    if ! [[ -f ${PACKED_NOTES_BASENAME}.tar.gz.age ]]
+    then
+        echo "No '${PACKED_NOTES_BASENAME}.tar.gz.age' file found, exiting..."
+        return 1
+    fi
+
+    if [[ -d "${HOME}/notes" ]]
+    then
+        printf "\n\e[31m%s\e[0m %s\n" "Error" \
+            "'${HOME}/notes' already exists. Stopping."
+        return 1
+    fi
+
+    if decrypt "${PACKED_NOTES_BASENAME}"
+    then
+        printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
+            "File decrypted to: ${PACKED_NOTES_BASENAME}.tar.gz"
+    else
+        printf "\n\e[31m%s\e[0m %s %s\n" "[Error]" \
+            "Couldn't decrypt encrypted notes files:" \
+            "'${PACKED_NOTES_BASENAME}.tar.gz.age'"
+        return 1
+    fi
+
+    if tar --extract --directory="$HOME" \
+        --file="${PACKED_NOTES_BASENAME}.tar.gz" &>/dev/null
+    then
+        rm "${PACKED_NOTES_BASENAME}.tar.gz" &>/dev/null
+        printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
+            "Unpacked: '$PACKED_NOTES_BASENAME.tar.gz'"
+        return 0
+    else
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Failed to decompress the decrypt '$PACKED_NOTES_BASENAME.tar.gz' file"
+        return 1
+    fi
+}
+
+open_notes() {
+    if command -v lf &>/dev/null
+    then
+        lf $HOME/notes
+    else
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Must have 'lf' installed to traverse notes"
+        return 1
+    fi
+
+    return 0
+}
+
+
 
 
 case $1 in
@@ -173,7 +214,8 @@ case $1 in
     "")            ensure_notes_dir && open_notes;;
     "--help"|"-h") display_help;;
     *)
-        echo -e "\n - Invalid use of the \`notes\` command -";
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Invalid use of the \`notes\` command"
         display_help
         exit 1
         ;;
diff --git a/ScriptsAddedToPath/store b/ScriptsAddedToPath/store
--- a/ScriptsAddedToPath/store
+++ b/ScriptsAddedToPath/store
@@ -19,164 +19,209 @@
 PACKED_STORE_BASENAME="packed_store"
 PASS_STORE_DIR="$HOME/.password-store"
 
+REQUIRED_COMMANDS=(printf age tar gzip gunzip)
+
+ensure_commands_installed()
+{
+    for cmd in ${REQUIRED_COMMANDS[@]}
+    do
+        if ! command -v $cmd &>/dev/null
+        then
+            printf "\n\n\e[31m%s %s\e[0m\n\n" \
+                "[!] Missing required command: '$cmd'."
+            return 1
+        fi
+    done
+
+    return 0
+}
+
+ensure_commands_installed || exit $?
+
 ensure_store_dir() {
     if [[ -d $PASS_STORE_DIR ]]
     then
         return 0
     else
-        echo "A '.password-store' directory must be placed in your home directory, exiting..."
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "'$PASS_STORE_DIR' directory must exist. Stopping."
         return 1
     fi
-}
-
-pack() {
-    for arg in "${@}";
-    do
-        case $arg in
-            "--clean" | "-c")
-                [[ -z $clean_flag ]] && {
-                    clean_flag=true
-                }
-            ;;
-            *)
-                [[ "$arg" == "pack" && -z "$skipped_command_input" ]] && {
-                    skipped_command_input=true
-                    continue
-                }
-            ;;
-        esac
-    done
-
-    ORIGINAL_PWD=$PWD
-    cd $HOME
-
-    # Export keys
-    gpg_keys_id="$(cat $PASS_STORE_DIR/.gpg-id)"
-    gpg --output $PASS_STORE_DIR/public.asc --armor --export $gpg_keys_id
-    gpg --output $PASS_STORE_DIR/private.asc --armor --export-secret-key $gpg_keys_id
-
-    echo "Archiving and Compressing password store and gpg keys..."
-    tar -czf $PACKED_STORE_BASENAME.tar.gz .password-store
-
-    mv $PACKED_STORE_BASENAME.tar.gz $ORIGINAL_PWD/ &>/dev/null
-    cd $ORIGINAL_PWD
-
-    echo "Encrypting Store..."
-
-    while :
-    do
-        # Encrypt the backup for transport
-        if openssl enc -a -aes-256-cbc -pbkdf2 --iter 1000000 \
-            -in $PACKED_STORE_BASENAME.tar.gz \
-            -out $PACKED_STORE_BASENAME.tar.gz.aes 2> /dev/null
-        then
-            good_encryption=true
-            break
-        else
-            echo -e "\n - Encryption keys don't match... try again - \n"
-        fi
-    done
-
-    # Remove the unencrypted .tar.gz file
-    shred -uz $PACKED_STORE_BASENAME.tar.gz
-
-    if [[ $good_encryption == true ]]
-    then
-        #
-        # Apply Flags
-        #
-        if [[ $clean_flag == true ]]; then
-            gpg --yes --delete-secret-key $gpg_keys_id 
-            gpg --yes --delete-key $gpg_keys_id 
-            rm -rf $PASS_STORE_DIR 
-        fi
-
-        echo "Store packed to '$PACKED_STORE_BASENAME.tar.gz.aes'"
-        return 0
-    else
-        echo "Had and issue encrypting '$PACKED_STORE_BASENAME.tar.gz'"
-        return 1
-    fi
-}
-
-unpack() {
-    if ! [[ -f $PACKED_STORE_BASENAME.tar.gz.aes ]]
-    then
-        echo "No '$PACKED_STORE_BASENAME.tar.gz.aes' file found, exiting..."
-        return 1
-    fi
-
-    if [[ -d $PASS_STORE_DIR ]]
-    then
-        read -p "'$PASS_STORE_DIR' already exists, are you sure you want to overwrite it? [y/N]: " overwrite_store
-        [[ $overwrite_store == "y" || $overwrite_store == "Y" || $overwrite_store == "yes" ]] || {
-            echo "Skipping unpack..."
-            return 1
-        }
-    fi
-
-    echo "Decrypting Store..."
-    while :
-    do
-        # Decrypt the backup
-        openssl enc -d -a -aes-256-cbc -pbkdf2 --iter 1000000 \
-            -in $PACKED_STORE_BASENAME.tar.gz.aes \
-            -out $PACKED_STORE_BASENAME.tar.gz 2> /dev/null
-
-        # Test if the file was decrypted correctly
-        tar --list --file $PACKED_STORE_BASENAME.tar.gz &>/dev/null \
-            && break \
-            || echo -e "\n - Incorrect decryption key... try again - \n"
-    done
-
-    mv $PACKED_STORE_BASENAME.tar.gz $HOME/ &>/dev/null
-    cd $HOME
-
-    if tar -xf $PACKED_STORE_BASENAME.tar.gz &>/dev/null
-    then
-        shred -uz $PACKED_STORE_BASENAME.tar.gz
-        echo "Store unpacked!"
-    else
-        echo "[ERROR] Failed to decompress the unencrypted '$PACKED_STORE_BASENAME.tar.gz' file"
-        return 1
-    fi
-
-    # Import and increase trust of keys
-    gpg --import $PASS_STORE_DIR/private.asc &>/dev/null
-    gpg --import $PASS_STORE_DIR/public.asc &>/dev/null
-
-    rm $PASS_STORE_DIR/private.asc
-    rm $PASS_STORE_DIR/public.asc
-
-    echo -e "\n----"
-    echo "Keys imported! Now we must increase their trust level, in the"
-    echo "the prompts below type: 'trust', '5', 'y', 'save'. Then you're done!"
-    echo -e "----\n"
-
-    gpg_keys_id="$(cat $PASS_STORE_DIR/.gpg-id)"
-    gpg --edit-key $gpg_keys_id
-
-    return 0
 }
 
 display_help() {
-    echo -e "\nUsage: store [COMMAND]"
-    echo -e "\nEasy encrypted backup of your password store and its correlated gpg keys."
+    printf "\nUsage: store [COMMAND]"
+    printf "\n%s\n" \
+        "Easy encrypted backup of your password store and its correlated gpg keys."
 
-    echo -e "\nCommands:"
-    printf "\t%-10s %-10s\n" "pack" "Export gpg keys and zip & encrypt them with '\$HOME/.password-store' into a packed_store.tar.gz.aes file"
-    printf "\t%-10s %-10s\n" "unpack" "Decrypt, unzip, and import the gpg keys and place the password store back in '\$HOME/.password-store'"
+    printf "\nCommands:"
+    printf "\n  %-12s %s" "pack" \
+        "Compress and symmetrically encrypt '\$Home/.password-store' and its correlating asymmetric keys."
+    printf "\n  %-12s %s" "unpack" \
+        "Decrypt and decompress passwords back into '\$Home/.password-store' and import asymmetric keys"
 
-    echo -e "\nCommand Flags:\n"
-    echo -e "\tpack:"
-    printf "\t    %-10s\t %-1s\n" "--clean" "removes '\$HOME/.password-store' and the gpg keys after creating packed_store.tar.gz.aes"
+    printf "\n\nExamples:"
+    printf "\n  \`store pack\`"
+    printf "\n  \`store unpack\`\n"
+}
 
-    echo -e "\nExamples:"
-    echo -e "\t\`store pack\`"
-    echo -e "\t\`store pack --clean\`"
-    echo -e "\t\`store unpack\`"
+encrypt()
+{
+    filename="$1"
 
-    echo ""
+    for attempt in {1..5}
+    do
+        if [[ $attempt -ne 1 ]]
+        then
+            printf "\n%s \e[36m%s\e[0m %s\n" "Attempt" "$attempt" "of 5"
+        fi
+
+        age --passphrase "${filename}.tar.gz" > "${filename}.tar.gz.age"
+
+        if [[ $? == 0 ]]
+        then
+            return 0
+        else
+            printf "\n\n\e[31m%s\e[0m %s\n\n" "[Error]" \
+                "Encryption failed... try again"
+        fi
+    done
+
+    return 1
+}
+
+pack() {
+    printf "\n\e[36m%s\e[0m %s\n" "Unlock password store:"
+    gpg_key_id="$(cat "${PASS_STORE_DIR}/.gpg-id")"
+    gpg --output "${PASS_STORE_DIR}/public.asc" --batch --yes --armor --export "$gpg_key_id"
+    gpg --output "${PASS_STORE_DIR}/private.asc" --batch --yes --armor --export-secret-key "$gpg_key_id"
+
+    if [[ -f "${PACKED_STORE_BASENAME}.tar.gz.age" ]] \
+    then
+        cp "${PACKED_STORE_BASENAME}.tar.gz.age" \
+            "${PACKED_STORE_BASENAME}.tar.gz.age.bak" &>/dev/null
+    fi
+
+    printf "\n\e[36m%s\e[0m %s\n" "Compressing store..."
+    if tar --create --gzip --directory="$HOME" \
+        --file="${PACKED_STORE_BASENAME}.tar.gz" .password-store &>/dev/null
+    then
+        printf "\n\e[36m%s\e[0m %s\n" "Encrypt store:"
+        if encrypt "${PACKED_STORE_BASENAME}"
+        then
+            rm "${PACKED_STORE_BASENAME}.tar.gz"
+            printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
+                "File packed to: ${PACKED_STORE_BASENAME}.tar.gz.age"
+            return 0
+        else
+            printf "\n\e[31m%s\e[0m %s %s\n" "[Error]" \
+                "Couldn't encrypt compressed notes file:" \
+                "'${PACKED_STORE_BASENAME}.tar.gz'"
+        fi
+    else
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Couldn't compress '$PASS_STORE_DIR' with tar. Stopping."
+        return 1
+    fi
+
+    if [[ -f "${PACKED_STORE_BASENAME}.tar.gz.age.bak" ]]
+    then
+        cp "${PACKED_STORE_BASENAME}.tar.gz.age.bak" \
+            "${PACKED_STORE_BASENAME}.tar.gz.age" &>/dev/null
+    fi
+    return 0
+}
+
+decrypt()
+{
+    filename="$1"
+
+    for attempt in {1..5}
+    do
+        if [[ $attempt -ne 1 ]]
+        then
+            printf "\n%s \e[36m%s\e[0m %s\n" "Attempt" "$attempt" "of 5"
+        fi
+
+        age --decrypt "${filename}.tar.gz.age" > "${filename}.tar.gz"
+
+        if tar --list --file="${PACKED_STORE_BASENAME}.tar.gz" &>/dev/null
+        then
+            return 0
+        else
+            printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+                "Incorrect decryption key... try again"
+        fi
+    done
+        
+    return 1
+}
+
+unpack() {
+    if ! [[ -f "${PACKED_STORE_BASENAME}.tar.gz.age" ]]
+    then
+        echo "No '${PACKED_STORE_BASENAME}.tar.gz.age' file found, exiting..."
+        return 1
+    fi
+
+    if [[ -d "$PASS_STORE_DIR" ]]
+    then
+        printf "\n\e[31m%s\e[0m %s\n" "Error" \
+            "'$PASS_STORE_DIR' already exists. Stopping."
+        return 1
+    fi
+
+    if decrypt "${PACKED_STORE_BASENAME}"
+    then
+        printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
+            "File decrypted to: ${PACKED_STORE_BASENAME}.tar.gz"
+    else
+        printf "\n\e[31m%s\e[0m %s %s\n" "[Error]" \
+            "Couldn't decrypt encrypted notes files:" \
+            "'${PACKED_STORE_BASENAME}.tar.gz.age'"
+        return 1
+    fi
+
+    if tar --extract --directory="$HOME" \
+        --file="${PACKED_STORE_BASENAME}.tar.gz" &>/dev/null
+    then
+        rm "${PACKED_STORE_BASENAME}.tar.gz" &>/dev/null
+        printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
+            "Unpacked: '$PACKED_STORE_BASENAME.tar.gz'"
+    else
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Failed to decompress the decrypt '$PACKED_STORE_BASENAME.tar.gz' file"
+        return 1
+    fi
+
+    gpg --import "${PASS_STORE_DIR}/private.asc" \
+        "${PASS_STORE_DIR}/public.asc" &>/dev/null
+    if [[ $? -ne 0 ]]
+    then
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Failed to import private and public keys. Stopping."
+        return 1
+    fi
+
+    printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
+        "Imported private and public keys"
+
+    rm "${PASS_STORE_DIR}/private.asc" "${PASS_STORE_DIR}/public.asc"
+
+    gpg_key_id="$(cat "${PASS_STORE_DIR}/.gpg-id")"
+    # Set ultimate trust non-interactively (use full fingerprint!)
+    echo "$gpg_key_id:6:" | gpg --import-ownertrust &>/dev/null
+    if [[ $? -ne 0 ]]
+    then
+        printf "\n\e[31m%s\e[0m %s\n" "[Error]" \
+            "Failed to set 'ultimate' trust level on imported keys."
+        return 1
+    fi
+
+    printf "\n\e[32m%s\e[0m %s\n" "[Success]" \
+        "Set keys trust level to 'ultimate'"
+
+    return 0
 }
 
 
